In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\data\raw-data\appartments.csv')

In [3]:
data.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."

In [4]:
data.columns

Index(['PropertyName', 'PropertySubName', 'NearbyLocations',
       'LocationAdvantages', 'Link', 'PriceDetails', 'TopFacilities'],
      dtype='object')

### Propert Name

In [5]:
data['PropertyName'].nunique()

247

property name contains the names of the different real estate societies in Gurgaon

### PropertySubname

In [6]:
data['PropertySubName']

0           2, 3, 4 BHK Apartment in Sector 113, Gurgaon
1              3, 4 BHK Apartment in Sector 111, Gurgaon
2      Land, 3, 4 BHK Independent Floor in Sector 63,...
3           2, 3, 4 BHK Apartment in Sector 108, Gurgaon
4        2, 3 BHK Independent Floor in Sector 93 Gurgaon
                             ...
242        2, 3, 4 BHK Apartment in DLF Phase 5, Gurgaon
243             1, 2 BHK Apartment in Sector 86, Gurgaon
244      2, 3, 4, 5 BHK Apartment in Sector 103, Gurgaon
245            2, 3 BHK Apartment in Sector 37D, Gurgaon
246             2, 3 BHK Apartment in Sector 84, Gurgaon
Name: PropertySubName, Length: 247, dtype: object

PropertSubName contains the types of appartment the society offers and the sector info

### NearbyLocations

In [7]:
data['NearbyLocations']

0      ['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...
1      ['DPSG Palam Vihar Gurugram', 'The NorthCap Un...
2      ['AIPL Business Club Sector 62', 'Heritage Xpe...
3      ['The Shikshiyan School', 'WTC Plaza', 'Luxus ...
4      ['Pranavananda Int. School', 'DLF Site central...
                             ...
242    ['Sector 42-43 Metro Station', 'Paras Hospital...
243    ['Aarvy Healthcare Super Speciality', "St. Xav...
244    ['Dwarka Expressway', 'S N International Schoo...
245    ['Suncity School', 'Gurugram Road', 'Dwarka Ex...
246    ['Sector 84 Road', 'Delhi Public School, Secto...
Name: NearbyLocations, Length: 247, dtype: object

NearbyLocations contains a list of some nearby locations

In [8]:
data['LocationAdvantages'].iloc[0]

"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"

In [9]:
data['NearbyLocations'].iloc[0]

"['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar', 'Park Hospital', 'Gurgaon Railway Station']"

-   LocationAdvantages contains dictionary with the name of the nearby location and the distance from the society. 
-   NearbyLocations is a subset of locations mentioned in LocationAdvantages
-   NearbyLocations can be dropped later

### Link

In [10]:
data['Link']

0      https://www.99acres.com/smartworld-one-dxp-sec...
1      https://www.99acres.com/m3m-crown-sector-111-g...
2      https://www.99acres.com/adani-brahma-samsara-v...
3      https://www.99acres.com/sobha-city-sector-108-...
4      https://www.99acres.com/signature-global-city-...
                             ...
242    https://www.99acres.com/dlf-princeton-estate-d...
243    https://www.99acres.com/pyramid-urban-homes-2-...
244    https://www.99acres.com/satya-the-hermitage-se...
245    https://www.99acres.com/bptp-spacio-sector-37d...
246    https://www.99acres.com/ss-the-coralwood-secto...
Name: Link, Length: 247, dtype: object

contains links to the website. links seem to be non functional - can be dropped later

### PriceDetails

In [11]:
data['PriceDetails'].iloc[0]

"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}"

Contains nested dict with room type and its details

### TopFacilities

In [12]:
data['TopFacilities'].iloc[0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

TopFacilities containsfacilities offered in the society. Can be used to segment socities based on luxury

## Recommender System - based on TopFacilities

In [13]:
df = data.copy()

In [14]:
df.drop(columns = ['NearbyLocations', 'Link'], inplace = True)      # drop unnecessary columns

In [15]:
df[['PropertyName', 'TopFacilities']]

,PropertyName,TopFacilities
0,Smartworld One DXP,"['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."
...,...,...
242,DLF Princeton Estate,"['Swimming Pool', 'Medical Centre', 'Laundry',..."
243,Pyramid Urban Homes 2,"['Shopping Centre', 'Community Hall', '24x7 Se..."
244,Satya The Hermitage,"['Bus Shelter', 'Swimming Pool', 'Business Lou..."
245,BPTP Spacio,"['Swimming Pool', 'Card Room', 'Piped Gas', 'P..."
246,SS The Coralwood,"['Swimming Pool', 'School', 'Solar Lighting', ..."

In [16]:
df['TopFacilities'].iloc[0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

In [17]:
import re
def extract_facilities(row):
    return re.findall("'(.*?)'", row)       # extract everything inside single inverted comas and return list

df['TopFacilities'] = df['TopFacilities'].apply(extract_facilities)

In [18]:
df.head()

,PropertyName,PropertySubName,LocationAdvantages,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...","{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...","{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",{'3 BHK': {'building_type': 'Independent Floor...,"[Terrace Garden, Gazebo, Fountain, Amphitheatr..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...","{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Volley Ball Court, Aerobics Ce..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","{'Pranavananda Int. School': '450 m', 'DLF Sit...",{'2 BHK': {'building_type': 'Independent Floor...,"[Mini Theatre, Doctor on Call, Concierge Servi..."

In [19]:
# convert the list into strings

df['TopFacilities'] = df['TopFacilities'].apply(' '.join)

In [20]:
df['TopFacilities'].iloc[0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

applying tfidf vectoriser to TopFacilities column

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english', ngram_range=(1,2))
tfidf_matrix = tfidf.fit_transform(df['TopFacilities'])

In [22]:
tfidf_matrix.toarray()

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.1438338,
        0.1438338],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]], shape=(247, 953))

In [23]:
# cosine similarity of each vector with allthe other vectors 

from sklearn.metrics.pairwise import cosine_similarity

cos_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [24]:
def recommend_properties(property_name, cosine_sim = cos_sim1):
    # get the index of the property name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]
    
    # similarity score of the idx item with respect to other items. Using enumerate to also pull the position of the elements
    sim_scores = list(enumerate(cos_sim1[idx]))
    
    

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse= True)       # sorting in descending order based on similarity score which is at index 1 in each tuple inside the big list 

    del sim_scores[0]       # remove the 0th index as it is the similarity score with itself
    
    # extract top 5 simarity scores and their indicies
    sim_scores = sim_scores[:5]

    # extract the indicies from the list of tupples sim_scores
    sim_property_indicies = [i[0] for i in sim_scores]

    recomendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[sim_property_indicies],
        'SimilarityScore': sim_property_indicies
    })

    return recomendations_df

In [25]:
print(recommend_properties("DLF The Arbour"))

           PropertyName  SimilarityScore
64      Ace Palm Floors               64
217         Yashika 104              217
93       JMS The Nation               93
154       India Rashtra              154
0    Smartworld One DXP                0

## Recommender system - based on PriceDetails

In [26]:
df.drop(index = 22, axis=1, inplace=True)           # bad row at index 22 preventing the use of literal_eval

In [27]:
from ast import literal_eval

df['PriceDetails'] = df['PriceDetails'].apply(literal_eval)         # converting the items in that column into python dict

In [28]:
type(df['PriceDetails'][0])

dict

In [29]:
data2 = df['PriceDetails'][2]
data2

{'3 BHK': {'building_type': 'Independent Floor',
  'area_type': 'Super Built-up Area',
  'area': '1,800 - 3,150 sq.ft.',
  'price-range': '₹ 2.43 - 15.75 Cr'},
 '4 BHK': {'building_type': 'Independent Floor',
  'area_type': 'Super Built-up Area',
  'area': '2,750 - 4,500 sq.ft.',
  'price-range': '₹ 3.36 - 22.5 Cr'},
 'Land': {'building_type': '',
  'area_type': 'Plot Area',
  'area': '500 - 4,329 sq.ft.',
  'price-range': '₹ 2.05 - 41.13 Cr'}}

In [30]:
refined_df = pd.DataFrame()

In [31]:
refined_df

Empty DataFrame
Columns: []
Index: []

In [32]:
def add_data_refined_df(data, row_index):
    for i in data.keys():       # navigate to each key in outer dict (eg 2 BHK and 3 BHK in data2 variable)
        for j in data[i]:           # inside inner dict, navigate to every inner keys( eg 'building_type', 'area_type', etc)
            col_name = f'{j}_{i}'       # create a column name (eg building_type_2 BHK, area_type_3 BHK)
            if col_name not in refined_df.columns:      # check if the column already exist
                refined_df[col_name] = None                # if the column doesn't exist, create a column and give it None value  
            refined_df.loc[row_index, col_name] = data[i][j]      # update the value of that column

    return refined_df

In [33]:
for i, data in enumerate(df['PriceDetails']):
    add_data_refined_df(data, i)

In [34]:
refined_df.head()

,building_type_2 BHK,area_type_2 BHK,area_2 BHK,price-range_2 BHK,building_type_3 BHK,area_type_3 BHK,area_3 BHK,price-range_3 BHK,building_type_4 BHK,area_type_4 BHK,...,area_1 BHK,price-range_1 BHK,building_type_1 RK,area_type_1 RK,area_1 RK,price-range_1 RK,building_type_6 BHK,area_type_6 BHK,area_6 BHK,price-range_6 BHK
0,Apartment,Carpet Area,"1,370 sq.ft.",₹ 2 - 2.4 Cr,Apartment,Carpet Area,"1,850 - 2,050 sq.ft.",₹ 2.25 - 3.59 Cr,Apartment,Carpet Area,...,None,None,None,None,None,None,None,None,None,None
1,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,"1,605 - 2,170 sq.ft.",₹ 2.2 - 3.03 Cr,Apartment,Super Built-up Area,...,None,None,None,None,None,None,None,None,None,None
2,NaN,NaN,NaN,NaN,Independent Floor,Super Built-up Area,"1,800 - 3,150 sq.ft.",₹ 2.43 - 15.75 Cr,Independent Floor,Super Built-up Area,...,None,None,None,None,None,None,None,None,None,None
3,Apartment,Super Built-up Area,"1,381 - 1,692 sq.ft.",₹ 1.55 - 3.21 Cr,Apartment,Super Built-up Area,"1,711 - 2,343 sq.ft.",₹ 1.76 - 4.79 Cr,Apartment,Super Built-up Area,...,None,None,None,None,None,None,None,None,None,None
4,Independent Floor,Carpet Area,"981 - 1,118 sq.ft.",₹ 93.01 L - 1.06 Cr,Independent Floor,Carpet Area,"1,235 - 1,530 sq.ft.",₹ 1.12 - 1.45 Cr,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None

In [35]:
cols_to_split = [
    'area_1 BHK', 'price-range_1 BHK',
    'area_2 BHK', 'price-range_2 BHK', 
    'area_3 BHK', 'price-range_3 BHK', 
    'area_4 BHK', 'price-range_4 BHK',
    'area_5 BHK', 'price-range_5 BHK',
    'area_5 BHK', 'price-range_5 BHK',
    'area_1 RK', 'price-range_1 RK',
    'area_Land', 'price-range_Land'
    ]

In [36]:
refined_df.head()

,building_type_2 BHK,area_type_2 BHK,area_2 BHK,price-range_2 BHK,building_type_3 BHK,area_type_3 BHK,area_3 BHK,price-range_3 BHK,building_type_4 BHK,area_type_4 BHK,...,area_1 BHK,price-range_1 BHK,building_type_1 RK,area_type_1 RK,area_1 RK,price-range_1 RK,building_type_6 BHK,area_type_6 BHK,area_6 BHK,price-range_6 BHK
0,Apartment,Carpet Area,"1,370 sq.ft.",₹ 2 - 2.4 Cr,Apartment,Carpet Area,"1,850 - 2,050 sq.ft.",₹ 2.25 - 3.59 Cr,Apartment,Carpet Area,...,None,None,None,None,None,None,None,None,None,None
1,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,"1,605 - 2,170 sq.ft.",₹ 2.2 - 3.03 Cr,Apartment,Super Built-up Area,...,None,None,None,None,None,None,None,None,None,None
2,NaN,NaN,NaN,NaN,Independent Floor,Super Built-up Area,"1,800 - 3,150 sq.ft.",₹ 2.43 - 15.75 Cr,Independent Floor,Super Built-up Area,...,None,None,None,None,None,None,None,None,None,None
3,Apartment,Super Built-up Area,"1,381 - 1,692 sq.ft.",₹ 1.55 - 3.21 Cr,Apartment,Super Built-up Area,"1,711 - 2,343 sq.ft.",₹ 1.76 - 4.79 Cr,Apartment,Super Built-up Area,...,None,None,None,None,None,None,None,None,None,None
4,Independent Floor,Carpet Area,"981 - 1,118 sq.ft.",₹ 93.01 L - 1.06 Cr,Independent Floor,Carpet Area,"1,235 - 1,530 sq.ft.",₹ 1.12 - 1.45 Cr,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None

In [37]:
row1 = refined_df.iloc[4]
row1

building_type_2 BHK       Independent Floor
area_type_2 BHK                 Carpet Area
area_2 BHK               981 - 1,118 sq.ft.
price-range_2 BHK       ₹ 93.01 L - 1.06 Cr
building_type_3 BHK       Independent Floor
area_type_3 BHK                 Carpet Area
area_3 BHK             1,235 - 1,530 sq.ft.
price-range_3 BHK          ₹ 1.12 - 1.45 Cr
building_type_4 BHK                     NaN
area_type_4 BHK                         NaN
area_4 BHK                              NaN
price-range_4 BHK                       NaN
building_type_Land                      NaN
area_type_Land                          NaN
area_Land                               NaN
price-range_Land                        NaN
building_type_5 BHK                    None
area_type_5 BHK                        None
area_5 BHK                             None
price-range_5 BHK                      None
building_type_1 BHK                    None
area_type_1 BHK                        None
area_1 BHK                             None
price-range_1 BHK                      None
building_type_1 RK                     None
area_type_1 RK                         None
area_1 RK                              None
price-range_1 RK                       None
building_type_6 BHK                    None
area_type_6 BHK                        None
area_6 BHK                             None
price-range_6 BHK                      None
Name: 4, dtype: object

In [38]:
def range_split_area(text):
    if text is not None:
        text_list = str(text).strip().split('-')
        if len(text_list) == 1:
            upper_area = float(text_list[0].strip().replace(',', '').split(' ')[0])
            lower_area = float(text_list[0].strip().replace(',', '').split(' ')[0])
        else:
            lower_area = float(text_list[0].strip().replace(',', '').split(' ')[0])
            upper_area = float(text_list[1].strip().replace(',', '').split(' ')[0])
        return lower_area, upper_area
    else:
        return None

In [39]:
refined_df.columns

Index(['building_type_2 BHK', 'area_type_2 BHK', 'area_2 BHK',
       'price-range_2 BHK', 'building_type_3 BHK', 'area_type_3 BHK',
       'area_3 BHK', 'price-range_3 BHK', 'building_type_4 BHK',
       'area_type_4 BHK', 'area_4 BHK', 'price-range_4 BHK',
       'building_type_Land', 'area_type_Land', 'area_Land', 'price-range_Land',
       'building_type_5 BHK', 'area_type_5 BHK', 'area_5 BHK',
       'price-range_5 BHK', 'building_type_1 BHK', 'area_type_1 BHK',
       'area_1 BHK', 'price-range_1 BHK', 'building_type_1 RK',
       'area_type_1 RK', 'area_1 RK', 'price-range_1 RK',
       'building_type_6 BHK', 'area_type_6 BHK', 'area_6 BHK',
       'price-range_6 BHK'],
      dtype='object')

In [40]:
area_columns_to_split = []
for col in refined_df.columns:
    if 'area' in col:
        if 'type' not in col:
            area_columns_to_split.append(col)

In [41]:
area_columns_to_split

['area_2 BHK',
 'area_3 BHK',
 'area_4 BHK',
 'area_Land',
 'area_5 BHK',
 'area_1 BHK',
 'area_1 RK',
 'area_6 BHK']

In [42]:
for col in area_columns_to_split:
    if f'{col}_lower' not in refined_df.columns:
        refined_df[f'{col}_lower'] = np.nan
        for i, area in enumerate(refined_df[col]):
            if area is not None:
                refined_df.loc[i, f'{col}_lower'] = refined_df[col].apply(range_split_area)[i][0]
    if f'{col}_upper' not in refined_df.columns:
        refined_df[f'{col}_upper'] = np.nan
        for i, area in enumerate(refined_df[col]):
            if area is not None:
                refined_df.loc[i, f'{col}_upper'] = refined_df[col].apply(range_split_area)[i][1]

In [43]:
refined_df.drop(columns = area_columns_to_split, inplace=True)

In [44]:
refined_df.columns

Index(['building_type_2 BHK', 'area_type_2 BHK', 'price-range_2 BHK',
       'building_type_3 BHK', 'area_type_3 BHK', 'price-range_3 BHK',
       'building_type_4 BHK', 'area_type_4 BHK', 'price-range_4 BHK',
       'building_type_Land', 'area_type_Land', 'price-range_Land',
       'building_type_5 BHK', 'area_type_5 BHK', 'price-range_5 BHK',
       'building_type_1 BHK', 'area_type_1 BHK', 'price-range_1 BHK',
       'building_type_1 RK', 'area_type_1 RK', 'price-range_1 RK',
       'building_type_6 BHK', 'area_type_6 BHK', 'price-range_6 BHK',
       'area_2 BHK_lower', 'area_2 BHK_upper', 'area_3 BHK_lower',
       'area_3 BHK_upper', 'area_4 BHK_lower', 'area_4 BHK_upper',
       'area_Land_lower', 'area_Land_upper', 'area_5 BHK_lower',
       'area_5 BHK_upper', 'area_1 BHK_lower', 'area_1 BHK_upper',
       'area_1 RK_lower', 'area_1 RK_upper', 'area_6 BHK_lower',
       'area_6 BHK_upper'],
      dtype='object')

In [45]:
refined_df.head()

,building_type_2 BHK,area_type_2 BHK,price-range_2 BHK,building_type_3 BHK,area_type_3 BHK,price-range_3 BHK,building_type_4 BHK,area_type_4 BHK,price-range_4 BHK,building_type_Land,...,area_Land_lower,area_Land_upper,area_5 BHK_lower,area_5 BHK_upper,area_1 BHK_lower,area_1 BHK_upper,area_1 RK_lower,area_1 RK_upper,area_6 BHK_lower,area_6 BHK_upper
0,Apartment,Carpet Area,₹ 2 - 2.4 Cr,Apartment,Carpet Area,₹ 2.25 - 3.59 Cr,Apartment,Carpet Area,₹ 3.24 - 4.56 Cr,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Apartment,Super Built-up Area,₹ 2.2 - 3.03 Cr,Apartment,Super Built-up Area,₹ 3.08 - 3.73 Cr,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Independent Floor,Super Built-up Area,₹ 2.43 - 15.75 Cr,Independent Floor,Super Built-up Area,₹ 3.36 - 22.5 Cr,,...,500.0,4329.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Apartment,Super Built-up Area,₹ 1.55 - 3.21 Cr,Apartment,Super Built-up Area,₹ 1.76 - 4.79 Cr,Apartment,Super Built-up Area,₹ 2.5 - 6.06 Cr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Independent Floor,Carpet Area,₹ 93.01 L - 1.06 Cr,Independent Floor,Carpet Area,₹ 1.12 - 1.45 Cr,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
def split_price(text):
    text_list = str(text).strip().split('-')
    if len(text_list) > 1:
        lower_price_text = text_list[0].strip()
        upper_price_text = text_list[1].strip()
        if 'L' in lower_price_text:
            lower_price = float(re.findall(r"\d+(?:\.\d+)?", lower_price_text)[0]) * 0.01
            upper_price = float(re.findall(r"\d+(?:\.\d+)?", upper_price_text)[0]) * 0.01
        else:
            lower_price = float(re.findall(r"\d+(?:\.\d+)?", lower_price_text)[0])
            upper_price = float(re.findall(r"\d+(?:\.\d+)?", upper_price_text)[0])
        return round(lower_price, 2), round(upper_price,2)

    elif len(text_list) == 1:
        if text_list[0] == 'Price on Request':
            lower_price = 'Price on Request'
            upper_price = 'Price on Request'
            return lower_price, upper_price
        elif (text_list[0] is not None) or (text_list[0] != 'nan'):
            price_text = text_list[0].strip()
            if 'L' in price_text:
                price = float(re.findall(r"\d+(?:\.\d+)?", price_text)[0])
                lower_price = price
                upper_price = price
                return round(lower_price,2), round(upper_price, 2)

In [47]:
pd.set_option('display.max_rows', None)

In [48]:
price_cols_to_split = []

for col in refined_df.columns:
    if 'price' in col:
        price_cols_to_split.append(col)

In [49]:
price_cols_to_split

['price-range_2 BHK',
 'price-range_3 BHK',
 'price-range_4 BHK',
 'price-range_Land',
 'price-range_5 BHK',
 'price-range_1 BHK',
 'price-range_1 RK',
 'price-range_6 BHK']

In [50]:
for col in price_cols_to_split:
    if f'{col}_lower' not in refined_df.columns:
        refined_df[f'{col}_lower'] = None
        for i, price in enumerate(refined_df[col]):
            if refined_df[col].apply(split_price)[i] is not None:
                refined_df.loc[i, f'{col}_lower'] = refined_df[col].apply(split_price)[i][0]
    if f'{col}_upper' not in refined_df.columns:
        refined_df[f'{col}_upper'] = None
        for i, price in enumerate(refined_df[col]):
            if refined_df[col].apply(split_price)[i] is not None:
                refined_df.loc[i, f'{col}_upper'] = refined_df[col].apply(split_price)[i][1]

In [51]:
pd.set_option('display.max_columns', None)

In [52]:
refined_df.shape

(246, 56)

In [53]:
refined_df[~refined_df['price-range_1 BHK'].isna()]

,building_type_2 BHK,area_type_2 BHK,price-range_2 BHK,building_type_3 BHK,area_type_3 BHK,price-range_3 BHK,building_type_4 BHK,area_type_4 BHK,price-range_4 BHK,building_type_Land,area_type_Land,price-range_Land,building_type_5 BHK,area_type_5 BHK,price-range_5 BHK,building_type_1 BHK,area_type_1 BHK,price-range_1 BHK,building_type_1 RK,area_type_1 RK,price-range_1 RK,building_type_6 BHK,area_type_6 BHK,price-range_6 BHK,area_2 BHK_lower,area_2 BHK_upper,area_3 BHK_lower,area_3 BHK_upper,area_4 BHK_lower,area_4 BHK_upper,area_Land_lower,area_Land_upper,area_5 BHK_lower,area_5 BHK_upper,area_1 BHK_lower,area_1 BHK_upper,area_1 RK_lower,area_1 RK_upper,area_6 BHK_lower,area_6 BHK_upper,price-range_2 BHK_lower,price-range_2 BHK_upper,price-range_3 BHK_lower,price-range_3 BHK_upper,price-range_4 BHK_lower,price-range_4 BHK_upper,price-range_Land_lower,price-range_Land_upper,price-range_5 BHK_lower,price-range_5 BHK_upper,price-range_1 BHK_lower,price-range_1 BHK_upper,price-range_1 RK_lower,price-range_1 RK_upper,price-range_6 BHK_lower,price-range_6 BHK_upper
21,Apartment,Super Built-up Area,₹ 1.9 - 9.06 Cr,Apartment,Super Built-up Area,₹ 2.45 - 27.12 Cr,Apartment,Super Built-up Area,₹ 10.53 - 38.9 Cr,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,Price on Request,Studio Apartment,Carpet Area,₹ 1.41 - 3.6 Cr,None,None,None,1448.41,1479.00,1946.00,4429.50,4429.00,6353.03,NaN,NaN,NaN,NaN,464.14,6367.71,460.09,588.00,NaN,NaN,1.9,9.06,2.45,27.12,10.53,38.9,None,None,None,None,Price on Request,Price on Request,1.41,3.6,None,None
23,Apartment,Carpet Area,₹ 1.29 - 3.6 Cr,Apartment,Carpet Area,₹ 1.62 - 5.72 Cr,Apartment,Carpet Area,₹ 2.61 - 7.67 Cr,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,₹ 1.98 - 2.38 Cr,NaN,NaN,NaN,None,None,None,817.30,1732.00,1025.05,2050.00,1657.10,2750.00,NaN,NaN,NaN,NaN,1510.00,1510.00,NaN,NaN,NaN,NaN,1.29,3.6,1.62,5.72,2.61,7.67,None,None,None,None,1.98,2.38,None,None,None,None
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Service Apartment,Carpet Area,Price on Request,Studio Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,569.95,639.59,438.63,1607.00,NaN,NaN,None,None,None,None,None,None,None,None,None,None,Price on Request,Price on Request,Price on Request,Price on Request,None,None
144,Independent Floor,Super Built-up Area,Price on Request,Independent Floor,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,1620.00,1620.00,1737.00,1737.00,NaN,NaN,NaN,NaN,NaN,NaN,837.00,1272.00,NaN,NaN,NaN,NaN,Price on Request,Price on Request,Price on Request,Price on Request,None,None,None,None,None,None,Price on Request,Price on Request,None,None,None,None
145,Service Apartment,Super Built-up Area,₹ 13.36 - 16 Cr,Service Apartment,Super Built-up Area,₹ 14 Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Service Apartment,Super Built-up Area,₹ 6.49 - 13.99 Cr,NaN,NaN,NaN,NaN,NaN,NaN,1406.00,1683.00,1473.00,1473.00,NaN,NaN,NaN,NaN,NaN,NaN,683.00,1472.00,NaN,NaN,NaN,NaN,13.36,16.0,None,None,None,None,None,None,None,None,6.49,13.99,None,None,None,None
174,Apartment,Super Built-up Area,₹ 43.82 - 48.3 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,₹ 29.26 - 30.24 L,NaN,NaN,NaN,NaN,NaN,NaN,626.00,690.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,418.00,432.00,NaN,NaN,NaN,NaN,43.82,48.3,None,None,None,None,None,None,None,None,29.26,30.24,None,None,None,None
176,Apartment,Super Built-up Area,Price on Request,Apartment,Super Built-up Area,Price on Request,Apartment,Carpet Area,Price on Request,,Plot Area,₹ 1.2 - 1.86 Cr,Apartment,Super Built-up Area,Price on Request,Apartment,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,1252.13,1701.64,1510.71,2028.00,1676.51,1965.18,1023.57,1581.93,3056.66,3056.66,918.00,1144.00,NaN,NaN,NaN,NaN,Price on Request,Price on Request,Price on Request,Price on Request,Price on Request,Price on Request,1.2,1.86,Price on Request,Price on Request,Price on Request,Price on Request,None,None,None,None
178,Apartment,Carpet Area,Price on Request,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,559.82,566.61,644.86,645.26,NaN,NaN,NaN,NaN,NaN,NaN,348.04,398.86,NaN,NaN,NaN,NaN,Price on Request,Price on Request,Price on Request,Price on Request,None,None,None,None,None,None,Price on Request,Price on Request,None,None,None,None
190,Apartment,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,519.22,644.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,496.90,496.90,NaN,NaN,NaN,NaN,Price on Request,Price on Request,None,None,None,None,None,None,None,None,Price on Request,Price on Request,None,None,None,None
197,Apartment,Carpet Area,₹ 1.22 - 1.71 Cr,Apartment,Carpet Area,₹ 2.34 - 3.85 Cr,Apartment,Carpet Area,₹ 1.91 - 2.69 Cr,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,990.28,1390.16,1291.67,2129.00,1840.63,2599.00,NaN,NaN,NaN,NaN,661.44,661.44,NaN,NaN,NaN,NaN,1.22,1.71,2.34,3.85,1.91,2.69,None,None,None,None,Price on Request,Price on Request,None,None,None,None
201,Apartment,Super Built-up Area,₹ 1 - 1.06 Cr,Apartment,Super Built-up Area,₹ 1.3 - 1.33 Cr,Apartment,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,₹ 70 L,NaN,NaN,NaN,NaN,NaN,NaN,1060.00,1125.00,1505.00,1545.00,1850.00,1870.00,NaN,NaN,NaN,NaN,825.00,825.00,NaN,NaN,NaN,NaN,1.0,1.06,1.3,1.33,Price on Request,Price on Request,None,None,None,None,70.0,70.0,None,None,None,None
203,Apartment,Carpet Area,₹ 25.19 - 28.32 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,₹ 16.56 L,NaN,NaN,NaN,NaN,NaN,NaN,514.40,577.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338.64,338.64,NaN,NaN,NaN,NaN,25.19,28.32,None,None,None,None,None,None,None,None,16.56,16.56,None,None,None,None
204,Apartment,Super Built-up Area,₹ 26.62 - 44.93 L,Apartment,Super Built-up Area,₹ 36.18 L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,₹ 17 L,NaN,NaN,NaN,NaN,NaN,NaN,548.00,925.00,745.00,745.00,NaN,NaN,NaN,NaN,NaN,NaN,350.00,350.00,NaN,NaN,NaN,NaN,26.62,44.93,36.18,36.18,None,None,None,None,None,None,17.0,17.0,None,None,None,None
215,Apartment,Carpet Area,Price on Request,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,497.98,497.98,763.00,763.00,NaN,NaN,NaN,NaN,NaN,NaN,301.28,301.28,NaN,NaN,NaN,NaN,Price on Request,Price on Request,Price on Request,Price on Request,None,None,None,None,None,None,Price on Request,Price on Request,None,None,None,None
216,Apartment,Carpet Area,Price on Request,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,557.78,557.78,692.12,692.12,NaN,NaN,NaN,NaN,NaN,NaN,583.61,583.61,NaN,NaN,NaN,NaN,Price on Request,Price on Request,Price on Request,Price on Request,None,None,None,None,None,None,Price on Request,Price on Request,None,None,None,None
235,Apartment,Super Built-up Area,₹ 77.88 - 86.1 L,Apartment,Super Built-up Area,₹ 1.13 - 1.3 Cr,Apartment,Super Built-up Area,₹ 1.45 - 1.46 Cr,NaN,NaN,NaN,Apartment,Super Built-up Area,Price on Request,Apartment,Super Built-up Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,1298.05,1435.00,1877.00,2160.00,2423.00,2425.00,NaN,NaN,4567.02,4567.02,907.62,907.62,NaN,NaN,NaN,NaN,77.88,86.1,1.13,1.3,1.45,1.46,None,None,Price on Request,Price on Request,Price on Request,Price on Request,None,None,None,None
239,Apartment,Super Built-up Area,₹ 2.05 Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Service Apartment,Super Built-up Area,₹ 1.39 - 1.41 Cr,Studio Apartment,Super Built-up Area,₹ 1.36 - 1.39 Cr,NaN,NaN,NaN,1360.67,1360.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,892.00,904.00,874.13,892.24,NaN,NaN,None,None,None,None,None,None,None,None,None,None,1.39,1.41,1.36,1.39,None,None
242,Apartment,Carpet Area,Price on Request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Carpet Area,₹ 23.45 - 27.86 L,NaN,NaN,NaN,NaN,NaN,NaN,500.00,625.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.00,398.00,NaN,NaN,NaN,NaN,Price on Request,Price on Request,None,None,None,None,None,None,None,None,23.45,27.86,None,None,None,None

In [54]:
refined_df.drop(columns=price_cols_to_split, inplace = True)

In [58]:
refined_df.head(20)

,building_type_2 BHK,area_type_2 BHK,building_type_3 BHK,area_type_3 BHK,building_type_4 BHK,area_type_4 BHK,building_type_Land,area_type_Land,building_type_5 BHK,area_type_5 BHK,building_type_1 BHK,area_type_1 BHK,building_type_1 RK,area_type_1 RK,building_type_6 BHK,area_type_6 BHK,area_2 BHK_lower,area_2 BHK_upper,area_3 BHK_lower,area_3 BHK_upper,area_4 BHK_lower,area_4 BHK_upper,area_Land_lower,area_Land_upper,area_5 BHK_lower,area_5 BHK_upper,area_1 BHK_lower,area_1 BHK_upper,area_1 RK_lower,area_1 RK_upper,area_6 BHK_lower,area_6 BHK_upper,price-range_2 BHK_lower,price-range_2 BHK_upper,price-range_3 BHK_lower,price-range_3 BHK_upper,price-range_4 BHK_lower,price-range_4 BHK_upper,price-range_Land_lower,price-range_Land_upper,price-range_5 BHK_lower,price-range_5 BHK_upper,price-range_1 BHK_lower,price-range_1 BHK_upper,price-range_1 RK_lower,price-range_1 RK_upper,price-range_6 BHK_lower,price-range_6 BHK_upper
0,Apartment,Carpet Area,Apartment,Carpet Area,Apartment,Carpet Area,None,None,None,None,None,None,None,None,None,None,1370.00,1370.00,1850.00,2050.00,2600.00,2600.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.4,2.25,3.59,3.24,4.56,None,None,None,None,None,None,None,None,None,None
1,NaN,NaN,Apartment,Super Built-up Area,Apartment,Super Built-up Area,None,None,None,None,None,None,None,None,None,None,NaN,NaN,1605.00,2170.00,2248.00,2670.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2.2,3.03,3.08,3.73,None,None,None,None,None,None,None,None,None,None
2,NaN,NaN,Independent Floor,Super Built-up Area,Independent Floor,Super Built-up Area,,Plot Area,None,None,None,None,None,None,None,None,NaN,NaN,1800.00,3150.00,2750.00,4500.00,500.0,4329.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2.43,15.75,3.36,22.5,2.05,41.13,None,None,None,None,None,None,None,None
3,Apartment,Super Built-up Area,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,None,None,None,None,None,None,None,None,1381.00,1692.00,1711.00,2343.00,2423.00,2963.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.55,3.21,1.76,4.79,2.5,6.06,None,None,None,None,None,None,None,None,None,None
4,Independent Floor,Carpet Area,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,981.00,1118.00,1235.00,1530.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,0.01,1.12,1.45,None,None,None,None,None,None,None,None,None,None,None,None
5,NaN,NaN,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,Apartment,Super Built-up Area,None,None,None,None,None,None,NaN,NaN,2290.00,2937.00,3243.00,12613.00,NaN,NaN,6096.00,7582.00,NaN,NaN,NaN,NaN,NaN,NaN,None,None,3.07,3.96,4.35,17.39,None,None,8.21,10.24,None,None,None,None,None,None
6,NaN,NaN,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,2015.00,2150.00,2250.00,2675.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,1.53,1.85,1.71,2.46,None,None,None,None,None,None,None,None,None,None
7,NaN,NaN,Apartment,Carpet Area,Apartment,Carpet Area,NaN,NaN,Apartment,Carpet Area,None,None,None,None,None,None,NaN,NaN,1347.00,2600.00,1692.00,3100.00,NaN,NaN,2275.00,4100.00,NaN,NaN,NaN,NaN,NaN,NaN,None,None,4.05,8.88,4.89,10.59,None,None,6.0,14.0,None,None,None,None,None,None
8,Independent Floor,Carpet Area,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,959.00,1145.00,1091.00,1535.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.26,1.51,0.86,0.04,None,None,None,None,None,None,None,None,None,None,None,None
9,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,1508.26,1508.26,2588.79,2588.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.82,3.5,2.0,6.01,None,None,None,None,None,None,None,None,None,None,None,None
10,Independent Floor,Carpet Area,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,1055.00,1055.00,1325.00,1525.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.05,1.5,1.35,1.84,None,None,None,None,None,None,None,None,None,None,None,None
11,NaN,NaN,NaN,NaN,Apartment,Super Built-up Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,NaN,3950.00,3950.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,7.0,7.31,None,None,None,None,None,None,None,None,None,None
12,Apartment,Carpet Area,Apartment,Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,1193.00,1200.00,1534.00,1534.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,1.31,None,None,None,None,None,None,None,None,None,None,None,None,None,None
13,Independent Floor,Carpet Area,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,546.12,546.12,653.17,653.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.01,83.0,0.99,0.01,None,None,None,None,None,None,None,None,None,None,None,None
14,NaN,NaN,NaN,NaN,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,NaN,1487.57,1558.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,2.0,2.41,None,None,None,None,None,None,None,None,None,None
15,NaN,NaN,Apartment,Carpet Area,Apartment,Carpet Area,NaN,NaN,Apartment,Carpet Area,None,None,None,None,None,None,NaN,NaN,1534.61,3030.00,2009.05,2689.26,NaN,NaN,3384.52,3384.52,NaN,NaN,NaN,NaN,NaN,NaN,None,None,4.5,10.87,4.6,13.45,None,None,4.77,11.54,None,None,None,None,None,None
16,Apartment,Super Built-up Area,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,1420.00,1420.00,1532.00,2155.00,2630.00,2677.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.49,1.5,1.61,3.49,2.78,4.34,None,None,None,None,None,None,None,None,None,None
17,Independent Floor,Carpet Area,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,500.00,560.00,755.00,770.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96,0.01,1.22,1.41,None,None,None,None,None,None,None,None,None,None,None,None
18,NaN,NaN,Apartment,Super Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,1300.00,1690.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,1.4,2.47,None,None,None,None,None,None,None,None,None,None,None,None
19,NaN,NaN,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,3525.00,3525.00,4550.00,6050.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,8.2,8.64,10.3,15.29,None,None,None,None,None,None,None,None,None,None

In [61]:
refined_df.head()

,building_type_2 BHK,area_type_2 BHK,building_type_3 BHK,area_type_3 BHK,building_type_4 BHK,area_type_4 BHK,building_type_Land,area_type_Land,building_type_5 BHK,area_type_5 BHK,building_type_1 BHK,area_type_1 BHK,building_type_1 RK,area_type_1 RK,building_type_6 BHK,area_type_6 BHK,area_2 BHK_lower,area_2 BHK_upper,area_3 BHK_lower,area_3 BHK_upper,area_4 BHK_lower,area_4 BHK_upper,area_Land_lower,area_Land_upper,area_5 BHK_lower,area_5 BHK_upper,area_1 BHK_lower,area_1 BHK_upper,area_1 RK_lower,area_1 RK_upper,area_6 BHK_lower,area_6 BHK_upper,price-range_2 BHK_lower,price-range_2 BHK_upper,price-range_3 BHK_lower,price-range_3 BHK_upper,price-range_4 BHK_lower,price-range_4 BHK_upper,price-range_Land_lower,price-range_Land_upper,price-range_5 BHK_lower,price-range_5 BHK_upper,price-range_1 BHK_lower,price-range_1 BHK_upper,price-range_1 RK_lower,price-range_1 RK_upper,price-range_6 BHK_lower,price-range_6 BHK_upper
0,Apartment,Carpet Area,Apartment,Carpet Area,Apartment,Carpet Area,None,None,None,None,None,None,None,None,None,None,1370.0,1370.0,1850.0,2050.0,2600.0,2600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.4,2.25,3.59,3.24,4.56,None,None,None,None,None,None,None,None,None,None
1,NaN,NaN,Apartment,Super Built-up Area,Apartment,Super Built-up Area,None,None,None,None,None,None,None,None,None,None,NaN,NaN,1605.0,2170.0,2248.0,2670.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2.2,3.03,3.08,3.73,None,None,None,None,None,None,None,None,None,None
2,NaN,NaN,Independent Floor,Super Built-up Area,Independent Floor,Super Built-up Area,,Plot Area,None,None,None,None,None,None,None,None,NaN,NaN,1800.0,3150.0,2750.0,4500.0,500.0,4329.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2.43,15.75,3.36,22.5,2.05,41.13,None,None,None,None,None,None,None,None
3,Apartment,Super Built-up Area,Apartment,Super Built-up Area,Apartment,Super Built-up Area,NaN,NaN,None,None,None,None,None,None,None,None,1381.0,1692.0,1711.0,2343.0,2423.0,2963.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.55,3.21,1.76,4.79,2.5,6.06,None,None,None,None,None,None,None,None,None,None
4,Independent Floor,Carpet Area,Independent Floor,Carpet Area,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,981.0,1118.0,1235.0,1530.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,0.01,1.12,1.45,None,None,None,None,None,None,None,None,None,None,None,None

In [63]:
refined_df = refined_df.replace('Price on Request', np.nan)

C:\Users\apaks\AppData\Local\Temp\ipykernel_2076\4278238450.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  refined_df = refined_df.replace('Price on Request', np.nan)

In [65]:
refined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 246 entries, 0 to 245
Data columns (total 48 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   building_type_2 BHK      121 non-null    object
 1   area_type_2 BHK          121 non-null    object
 2   building_type_3 BHK      186 non-null    object
 3   area_type_3 BHK          186 non-null    object
 4   building_type_4 BHK      144 non-null    object
 5   area_type_4 BHK          144 non-null    object
 6   building_type_Land       48 non-null     object
 7   area_type_Land           48 non-null     object
 8   building_type_5 BHK      50 non-null     object
 9   area_type_5 BHK          50 non-null     object
 10  building_type_1 BHK      18 non-null     object
 11  area_type_1 BHK          18 non-null     object
 12  building_type_1 RK       3 non-null      object
 13  area_type_1 RK           3 non-null      object
 14  building_type_6 BHK      4 non-null      object
 15  area_type_6 BHK          4 non-null      object
 16  area_2 BHK_lower         121 non-null    float64
 17  area_2 BHK_upper         121 non-null    float64
 18  area_3 BHK_lower         186 non-null    float64
 19  area_3 BHK_upper         186 non-null    float64
 20  area_4 BHK_lower         144 non-null    float64
 21  area_4 BHK_upper         144 non-null    float64
 22  area_Land_lower          48 non-null     float64
 23  area_Land_upper          48 non-null     float64
 24  area_5 BHK_lower         50 non-null     float64
 25  area_5 BHK_upper         50 non-null     float64
 26  area_1 BHK_lower         18 non-null     float64
 27  area_1 BHK_upper         18 non-null     float64
 28  area_1 RK_lower          3 non-null      float64
 29  area_1 RK_upper          3 non-null      float64
 30  area_6 BHK_lower         4 non-null      float64
 31  area_6 BHK_upper         4 non-null      float64
 32  price-range_2 BHK_lower  84 non-null     float64
 33  price-range_2 BHK_upper  84 non-null     float64
 34  price-range_3 BHK_lower  139 non-null    float64
 35  price-range_3 BHK_upper  139 non-null    float64
 36  price-range_4 BHK_lower  99 non-null     float64
 37  price-range_4 BHK_upper  99 non-null     float64
 38  price-range_Land_lower   38 non-null     float64
 39  price-range_Land_upper   38 non-null     float64
 40  price-range_5 BHK_lower  24 non-null     float64
 41  price-range_5 BHK_upper  24 non-null     float64
 42  price-range_1 BHK_lower  8 non-null      float64
 43  price-range_1 BHK_upper  8 non-null      float64
 44  price-range_1 RK_lower   2 non-null      float64
 45  price-range_1 RK_upper   2 non-null      float64
 46  price-range_6 BHK_lower  2 non-null      float64
 47  price-range_6 BHK_upper  2 non-null      float64
dtypes: float64(32), object(16)
memory usage: 102.3+ KB

In [68]:
refined_df = refined_df.replace({None: np.nan})

In [73]:
cat_columns = refined_df.select_dtypes(include='object').columns

cat_columns

Index(['building_type_2 BHK', 'area_type_2 BHK', 'building_type_3 BHK',
       'area_type_3 BHK', 'building_type_4 BHK', 'area_type_4 BHK',
       'building_type_Land', 'area_type_Land', 'building_type_5 BHK',
       'area_type_5 BHK', 'building_type_1 BHK', 'area_type_1 BHK',
       'building_type_1 RK', 'area_type_1 RK', 'building_type_6 BHK',
       'area_type_6 BHK'],
      dtype='object')

In [75]:
# one hot encoding using pd.dumies
ohe_df = pd.get_dummies(data = refined_df, columns= cat_columns, drop_first=True)

In [76]:
ohe_df.shape

(246, 54)

In [77]:
ohe_df.fillna(0, inplace = True)

In [79]:
ohe_df.head()

,area_2 BHK_lower,area_2 BHK_upper,area_3 BHK_lower,area_3 BHK_upper,area_4 BHK_lower,area_4 BHK_upper,area_Land_lower,area_Land_upper,area_5 BHK_lower,area_5 BHK_upper,area_1 BHK_lower,area_1 BHK_upper,area_1 RK_lower,area_1 RK_upper,area_6 BHK_lower,area_6 BHK_upper,price-range_2 BHK_lower,price-range_2 BHK_upper,price-range_3 BHK_lower,price-range_3 BHK_upper,price-range_4 BHK_lower,price-range_4 BHK_upper,price-range_Land_lower,price-range_Land_upper,price-range_5 BHK_lower,price-range_5 BHK_upper,price-range_1 BHK_lower,price-range_1 BHK_upper,price-range_1 RK_lower,price-range_1 RK_upper,price-range_6 BHK_lower,price-range_6 BHK_upper,building_type_2 BHK_Independent Floor,building_type_2 BHK_Service Apartment,area_type_2 BHK_Carpet Area,area_type_2 BHK_Super Built-up Area,building_type_3 BHK_Independent Floor,building_type_3 BHK_Service Apartment,building_type_3 BHK_Villa,area_type_3 BHK_Carpet Area,area_type_3 BHK_Super Built-up Area,building_type_4 BHK_Independent Floor,building_type_4 BHK_Villa,area_type_4 BHK_Carpet Area,area_type_4 BHK_Super Built-up Area,building_type_5 BHK_Independent Floor,building_type_5 BHK_Villa,area_type_5 BHK_Carpet Area,area_type_5 BHK_Super Built-up Area,building_type_1 BHK_Service Apartment,area_type_1 BHK_Super Built-up Area,area_type_1 RK_Super Built-up Area,building_type_6 BHK_Villa,area_type_6 BHK_Super Built-up Area
0,1370.0,1370.0,1850.0,2050.0,2600.0,2600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.00,2.40,2.25,3.59,3.24,4.56,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False
1,0.0,0.0,1605.0,2170.0,2248.0,2670.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,2.20,3.03,3.08,3.73,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False
2,0.0,0.0,1800.0,3150.0,2750.0,4500.0,500.0,4329.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,2.43,15.75,3.36,22.50,2.05,41.13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,False,True,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,False
3,1381.0,1692.0,1711.0,2343.0,2423.0,2963.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.55,3.21,1.76,4.79,2.50,6.06,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False
4,981.0,1118.0,1235.0,1530.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.93,0.01,1.12,1.45,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [88]:
# scalling the data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

ohe_df_scaled = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=df['PropertyName'])

In [89]:
ohe_df_scaled.head()

,area_2 BHK_lower,area_2 BHK_upper,area_3 BHK_lower,area_3 BHK_upper,area_4 BHK_lower,area_4 BHK_upper,area_Land_lower,area_Land_upper,area_5 BHK_lower,area_5 BHK_upper,area_1 BHK_lower,area_1 BHK_upper,area_1 RK_lower,area_1 RK_upper,area_6 BHK_lower,area_6 BHK_upper,price-range_2 BHK_lower,price-range_2 BHK_upper,price-range_3 BHK_lower,price-range_3 BHK_upper,price-range_4 BHK_lower,price-range_4 BHK_upper,price-range_Land_lower,price-range_Land_upper,price-range_5 BHK_lower,price-range_5 BHK_upper,price-range_1 BHK_lower,price-range_1 BHK_upper,price-range_1 RK_lower,price-range_1 RK_upper,price-range_6 BHK_lower,price-range_6 BHK_upper,building_type_2 BHK_Independent Floor,building_type_2 BHK_Service Apartment,area_type_2 BHK_Carpet Area,area_type_2 BHK_Super Built-up Area,building_type_3 BHK_Independent Floor,building_type_3 BHK_Service Apartment,building_type_3 BHK_Villa,area_type_3 BHK_Carpet Area,area_type_3 BHK_Super Built-up Area,building_type_4 BHK_Independent Floor,building_type_4 BHK_Villa,area_type_4 BHK_Carpet Area,area_type_4 BHK_Super Built-up Area,building_type_5 BHK_Independent Floor,building_type_5 BHK_Villa,area_type_5 BHK_Carpet Area,area_type_5 BHK_Super Built-up Area,building_type_1 BHK_Service Apartment,area_type_1 BHK_Super Built-up Area,area_type_1 RK_Super Built-up Area,building_type_6 BHK_Villa,area_type_6 BHK_Super Built-up Area
PropertyName,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,1.223499,1.020101,0.553787,0.370864,0.602838,0.212073,-0.447044,-0.371421,-0.468954,-0.460463,-0.252266,-0.169584,-0.105157,-0.10253,-0.125582,-0.118934,-0.286003,-0.281045,-0.017523,0.045548,0.383381,0.242019,-0.195702,-0.224633,-0.248049,-0.235915,-0.1284,-0.134584,-0.090521,-0.082725,-0.077649,-0.073387,-0.289310,-0.063888,2.455315,-0.726602,-0.372678,-0.063888,-0.171139,2.085144,-1.067301,-0.254824,-0.236208,2.848001,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
M3M Crown,-0.893541,-0.896660,0.293086,0.472749,0.382746,0.243172,-0.447044,-0.371421,-0.468954,-0.460463,-0.252266,-0.169584,-0.105157,-0.10253,-0.125582,-0.118934,-0.368869,-0.374931,-0.023067,-0.014143,0.341443,0.108677,-0.195702,-0.224633,-0.248049,-0.235915,-0.1284,-0.134584,-0.090521,-0.082725,-0.077649,-0.073387,-0.289310,-0.063888,-0.407280,-0.726602,-0.372678,-0.063888,-0.171139,-0.479583,0.936943,-0.254824,-0.236208,-0.351123,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Adani Brahma Samsara Vilasa,-0.893541,-0.896660,0.500583,1.304803,0.696627,1.056178,0.369534,1.828502,-0.468954,-0.460463,-0.252266,-0.169584,-0.105157,-0.10253,-0.125582,-0.118934,-0.368869,-0.374931,0.002434,1.341680,0.414835,3.124152,0.643876,6.365780,-0.248049,-0.235915,-0.1284,-0.134584,-0.090521,-0.082725,-0.077649,-0.073387,-0.289310,-0.063888,-0.407280,-0.726602,2.683282,-0.063888,-0.171139,-0.479583,0.936943,3.924283,-0.236208,-0.351123,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Sobha City,1.240497,1.470610,0.405879,0.619632,0.492166,0.373342,-0.447044,-0.371421,-0.468954,-0.460463,-0.252266,-0.169584,-0.105157,-0.10253,-0.125582,-0.118934,-0.304648,-0.249359,-0.071852,0.173455,0.189416,0.483000,-0.195702,-0.224633,-0.248049,-0.235915,-0.1284,-0.134584,-0.090521,-0.082725,-0.077649,-0.073387,-0.289310,-0.063888,-0.407280,1.376269,-0.372678,-0.063888,-0.171139,-0.479583,0.936943,-0.254824,-0.236208,-0.351123,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Signature Global City 93,0.622383,0.667529,-0.100626,-0.070634,-1.022842,-0.943016,-0.447044,-0.371421,-0.468954,-0.460463,-0.252266,-0.169584,-0.105157,-0.10253,-0.125582,-0.118934,-0.330337,-0.374540,-0.142811,-0.182555,-0.465873,-0.490563,-0.195702,-0.224633,-0.248049,-0.235915,-0.1284,-0.134584,-0.090521,-0.082725,-0.077649,-0.073387,3.456497,-0.063888,2.455315,-0.726602,2.683282,-0.063888,-0.171139,2.085144,-1.067301,-0.254824,-0.236208,-0.351123,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111

calculate cosine similarity now for each row with the other row

In [91]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim2 = cosine_similarity(ohe_df_scaled)
cos_sim2.shape

(246, 246)

In [92]:
cos_sim2

array([[ 1.        , -0.25244265, -0.14507629, ..., -0.15290326,
        -0.11730221, -0.02601727],
       [-0.25244265,  1.        ,  0.14488951, ..., -0.16450169,
        -0.03845145, -0.11064311],
       [-0.14507629,  0.14488951,  1.        , ..., -0.12363888,
        -0.28331451, -0.27257777],
       ...,
       [-0.15290326, -0.16450169, -0.12363888, ...,  1.        ,
        -0.04024816,  0.0363054 ],
       [-0.11730221, -0.03845145, -0.28331451, ..., -0.04024816,
         1.        ,  0.9643767 ],
       [-0.02601727, -0.11064311, -0.27257777, ...,  0.0363054 ,
         0.9643767 ,  1.        ]], shape=(246, 246))

In [157]:
def recommend_properties2(property_name, top_n=5):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cos_sim2[ohe_df_scaled.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = ohe_df_scaled.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

In [158]:
recommend_properties2('M3M Crown')

             PropertyName  SimilarityScore
0          DLF The Primus         0.989396
1          DLF The Ultima         0.986111
2  Conscient Heritage Max         0.984735
3          Bestech Altura         0.975981
4              ATS Kocoon         0.973975

In [ ]:
def recommend_properties(property_name, cosine_sim = cos_sim1):
    # get the index of the property name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]
    
    # similarity score of the idx item with respect to other items. Using enumerate to also pull the position of the elements
    sim_scores = list(enumerate(cos_sim1[idx]))
    
    

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse= True)       # sorting in descending order based on similarity score which is at index 1 in each tuple inside the big list 

    del sim_scores[0]       # remove the 0th index as it is the similarity score with itself
    
    # extract top 5 simarity scores and their indicies
    sim_scores = sim_scores[:5]

    # extract the indicies from the list of tupples sim_scores
    sim_property_indicies = [i[0] for i in sim_scores]

    recomendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[sim_property_indicies],
        'SimilarityScore': sim_property_indicies
    })

    return recomendations_df