In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

### Map view

In [ ]:
df = pd.read_csv(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\data\preprocessed-data\gurgaon_properties_with_lat_long.csv')

In [ ]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,lat,lon
0,flat,sector 83,1.18,3,3,2,relatively new,1612.0,0,0,unfurnished,budget,high-rise,28.398567,76.964691
1,flat,sector 62,4.00,3,3,3,new,2353.0,1,0,semifurnished,budget,high-rise,28.413909,77.088594
2,flat,sector 85,1.10,2,2,3+,relatively new,1459.0,0,1,unfurnished,luxury,low-rise,28.404180,76.951343
3,flat,sector 91,0.89,2,2,3+,relatively new,1297.0,0,0,semifurnished,budget,medium-rise,28.401383,76.922532
4,flat,sector 7,0.48,3,2,1,new,889.0,0,0,unfurnished,budget,low-rise,28.464374,77.014294

In [ ]:
df['price_per_sqft'] = round((df['price']/df['built_up_area'])*10000000, 2)

In [ ]:
group_df = df1.groupby('sector')[['price', 'built_up_area', 'price_per_sqft', 'lat', 'lon']].mean()

In [7]:
fig = px.scatter_map(data_frame = group_df, lat = 'lat', lon='lon', color='price_per_sqft', size = 'built_up_area', color_continuous_scale = px.colors.cyclical.IceFire, zoom = 10, map_style='open-street-map', text = group_df.index)

fig.show()

In [8]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,lat,lon,price_per_sqft
0,flat,sector 83,1.18,3,3,2,relatively new,1612.0,0,0,unfurnished,budget,high-rise,28.398567,76.964691,7320.10
1,flat,sector 62,4.00,3,3,3,new,2353.0,1,0,semifurnished,budget,high-rise,28.413909,77.088594,16999.58
2,flat,sector 85,1.10,2,2,3+,relatively new,1459.0,0,1,unfurnished,luxury,low-rise,28.404180,76.951343,7539.41
3,flat,sector 91,0.89,2,2,3+,relatively new,1297.0,0,0,semifurnished,budget,medium-rise,28.401383,76.922532,6861.99
4,flat,sector 7,0.48,3,2,1,new,889.0,0,0,unfurnished,budget,low-rise,28.464374,77.014294,5399.33

In [15]:
type = ['flat', 'house']

In [ ]:
df['property_type'].isin(type)

0       True
1       True
2       True
3       True
4       True
        ...
3494    True
3495    True
3496    True
3497    True
3498    True
Name: property_type, Length: 3499, dtype: bool

In [ ]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,lat,lon,price_per_sqft
0,flat,sector 83,1.18,3,3,2,relatively new,1612.0,0,0,unfurnished,budget,high-rise,28.398567,76.964691,7320.10
1,flat,sector 62,4.00,3,3,3,new,2353.0,1,0,semifurnished,budget,high-rise,28.413909,77.088594,16999.58
2,flat,sector 85,1.10,2,2,3+,relatively new,1459.0,0,1,unfurnished,luxury,low-rise,28.404180,76.951343,7539.41
3,flat,sector 91,0.89,2,2,3+,relatively new,1297.0,0,0,semifurnished,budget,medium-rise,28.401383,76.922532,6861.99
4,flat,sector 7,0.48,3,2,1,new,889.0,0,0,unfurnished,budget,low-rise,28.464374,77.014294,5399.33

In [18]:
df.shape

(3499, 16)

### Wordcloud 
- for features columns

In [20]:
df1 = pd.read_csv(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\data\preprocessed-data\gurgaon_properties_cleaned_v1.csv')

In [29]:
wordcloud_df = df1[['sector', 'features']]