In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\Data\gurgaon_properties.csv')

In [3]:
df.head()

,Unnamed: 0.1,Unnamed: 0,property_name,property_type,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,0,707,8 Bedroom House for sale in Sector 105 Gurgaon,house,independent,0.60,11102.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),8,...,not available,"C 93 B, Sector 105 Gurgaon, Gurgaon, Haryana",3.0,West,0 to 1 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Bhar...",Property with modern upgradesPlease write a pr...,"['9 Fan', '17 Light', 'No AC', 'No Bed', 'No C...","['Private Garden / Terrace', 'Park']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,1,774,3 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,1.18,6801.0,1735.04,Super Built up area 1735(161.19 sq.m.)Carpet a...,3,...,not available,"Sector 83 Gurgaon, Gurgaon, Haryana",14.0,north,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Vatika gurgaon 21 is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,2,441,3 BHK Flat in Sector 62 Gurgaon,flat,emaar digihomes,4.00,14871.0,2689.8,Super Built up area 2588.79(240.51 sq.m.),3,...,servant room,"1103, Sector 62 Gurgaon, Gurgaon, Haryana",18.0,north,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",Emaar digihomes is one of gurgaon's most sough...,"['6 Fan', '7 Light', '8 AC', '1 Modular Kitche...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,3,1567,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.10,6318.0,1741.06,Super Built up area 1741(161.74 sq.m.)Carpet a...,2,...,store room,"Tower T - 2, Sector 85 Gurgaon, Gurgaon, Haryana",3.0,south-east,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","This 2 bhk flat is located in ss the leaf, whi...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
4,4,1178,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,0.89,6339.0,1404.01,Super Built up area 1404(130.44 sq.m.)Carpet a...,2,...,others,"Sector 91 Gurgaon, Gurgaon, Haryana",9.0,east,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",Tarc maceo is one of gurgaon's most sought aft...,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."

In [4]:
df.drop(columns = ['Unnamed: 0.1', 'Unnamed: 0'], inplace = True)

In [5]:
df.head()

,property_name,property_type,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,8 Bedroom House for sale in Sector 105 Gurgaon,house,independent,0.60,11102.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),8,4,3,not available,"C 93 B, Sector 105 Gurgaon, Gurgaon, Haryana",3.0,West,0 to 1 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Bhar...",Property with modern upgradesPlease write a pr...,"['9 Fan', '17 Light', 'No AC', 'No Bed', 'No C...","['Private Garden / Terrace', 'Park']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,1.18,6801.0,1735.04,Super Built up area 1735(161.19 sq.m.)Carpet a...,3,3,2,not available,"Sector 83 Gurgaon, Gurgaon, Haryana",14.0,north,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Vatika gurgaon 21 is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 62 Gurgaon,flat,emaar digihomes,4.00,14871.0,2689.8,Super Built up area 2588.79(240.51 sq.m.),3,3,3,servant room,"1103, Sector 62 Gurgaon, Gurgaon, Haryana",18.0,north,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",Emaar digihomes is one of gurgaon's most sough...,"['6 Fan', '7 Light', '8 AC', '1 Modular Kitche...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.10,6318.0,1741.06,Super Built up area 1741(161.74 sq.m.)Carpet a...,2,2,3+,store room,"Tower T - 2, Sector 85 Gurgaon, Gurgaon, Haryana",3.0,south-east,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","This 2 bhk flat is located in ss the leaf, whi...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
4,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,0.89,6339.0,1404.01,Super Built up area 1404(130.44 sq.m.)Carpet a...,2,2,3+,others,"Sector 91 Gurgaon, Gurgaon, Haryana",9.0,east,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",Tarc maceo is one of gurgaon's most sought aft...,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."

In [6]:
df.shape

(3961, 20)

In [7]:
# duplicate rows
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price_in_cr          20
price_per_sqft       20
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

extract sector from property name

In [9]:
df[df['property_name'].str.lower().str.contains('sector')]

,property_name,property_type,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,8 Bedroom House for sale in Sector 105 Gurgaon,house,independent,0.60,11102.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),8,4,3,not available,"C 93 B, Sector 105 Gurgaon, Gurgaon, Haryana",3.0,West,0 to 1 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Bhar...",Property with modern upgradesPlease write a pr...,"['9 Fan', '17 Light', 'No AC', 'No Bed', 'No C...","['Private Garden / Terrace', 'Park']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,1.18,6801.0,1735.04,Super Built up area 1735(161.19 sq.m.)Carpet a...,3,3,2,not available,"Sector 83 Gurgaon, Gurgaon, Haryana",14.0,north,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Vatika gurgaon 21 is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 62 Gurgaon,flat,emaar digihomes,4.00,14871.0,2689.8,Super Built up area 2588.79(240.51 sq.m.),3,3,3,servant room,"1103, Sector 62 Gurgaon, Gurgaon, Haryana",18.0,north,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",Emaar digihomes is one of gurgaon's most sough...,"['6 Fan', '7 Light', '8 AC', '1 Modular Kitche...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.10,6318.0,1741.06,Super Built up area 1741(161.74 sq.m.)Carpet a...,2,2,3+,store room,"Tower T - 2, Sector 85 Gurgaon, Gurgaon, Haryana",3.0,south-east,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","This 2 bhk flat is located in ss the leaf, whi...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
4,2 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,0.89,6339.0,1404.01,Super Built up area 1404(130.44 sq.m.)Carpet a...,2,2,3+,others,"Sector 91 Gurgaon, Gurgaon, Haryana",9.0,east,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",Tarc maceo is one of gurgaon's most sought aft...,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.12,6453.0,1735.63,Super Built up area 1741(161.74 sq.m.)Built Up...,2,2,3,others,"Sector 85 Gurgaon, Gurgaon, Haryana",10.0,east,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Located in sector 85 gurgaon. Spread over 11.0...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3956,3 BHK Flat in Sector 103 Gurgaon,flat,indiabulls centrum park,1.35,7541.0,1790.21,Super Built up area 1790(166.3 sq.m.),3,3,3+,study room,"Sector 103 Gurgaon, Gurgaon, Haryana",3.0,north-east,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",Check out this 3 bhk apartment for sale in ind...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
3958,2 BHK Flat in Sector 108 Gurgaon,flat,sobha city,2.10,13975.0,1502.68,Super Built up area 1381(128.3 sq.m.),2,2,2,not available,"A4 Tower, Sector 108 Gurgaon, Gurgaon, Haryana",3.0,NaN,Oct 2024,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",This is under construction property with posse...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
3959,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,1.75,7641.0,2290.28,Super Built up area 2290(212.75 sq.m.),3,4,3+,servant room,"N/a, Sector 104 Gurgaon, Gurgaon, Haryana",11.0,south-east,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","This 3 bhk flat is located in ats triumph, whi...",[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction5 out of..."
3960,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,0.72,5522.0,1303.88,Built Up area: 1295 (120.31 sq.m.),2,2,0,not available,"E906, Sector-79, Sector 79 Gurgaon, Gurgaon, H...",9.0,NaN,Under Construction,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",Construction linked booking. First holder. Pai...,[],NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."

In [10]:
# create new column as sector

sector = df['property_name'].str.strip().str.lower().str.split('in').str.get(1).str.replace('gurgaon', '').str.strip()

In [11]:
df.insert(loc = 3, column = 'sector', value=sector)

In [12]:
pd.set_option('display.max_rows', None)

In [13]:
df[~df['sector'].str.contains('sector')]['sector'].value_counts()

sector
sohna                                                 163
nirvana country                                        53
palam vihar                                            50
dlf phase 2                                            43
dlf phase 1                                            43
sushant lok phase 1                                    31
laxman vihar                                           27
dlf phase 4                                            26
dlf phase 3                                            22
sushant lok phase 3                                    16
rajendra park                                          14
gwal pahari                                            14
dlf phase 5                                            14
laxman vihar phase 2                                   13
sohna road                                             12
uppals southend                                        12
ashok vihar phase 3 extension                          11
south city 1                                            9
ashok vihar phase 2                                     9
dwarka expressway                                       8
palam vihar extension                                   8
c block sushant lok phase 1                             8
malibu town                                             8
mehrauli  road                                          8
surat nagar 1                                           7
mianwali colony                                         7
new colony                                              7
rajiv nagar                                             6
jyoti park                                              6
jacobpura                                               6
ashok vihar                                             6
new palam vihar                                         5
saraswati vihar                                         5
sushant lok phase 2                                     5
dayanand colony                                         5
manesar                                                 5
subhash nagar                                           5
ansal plaza                                             5
greenwood city                                          5
arjun nagar                                             5
chakkarpur                                              5
imt manesar                                             4
garhi harsaru                                           4
krishna colony                                          4
suncity                                                 4
shivaji nagar                                           4
bhondsi                                                 4
devilal colony                                          4
ravi nagar                                              4
madanpuri                                               4
bhim nagar                                              4
new                                                     4
surya vihar                                             4
vishnu garden                                           4
dharam colony                                           4
baldev nagar                                            4
valley view estate                                      4
adarsh nagar                                            4
shivpuri                                                4
gandhi nagar                                            3
prem nagar                                              3
mg road                                                 3
laxmi garden                                            3
shakti nagar                                            3
patel nagar                                             3
b block sushant lok phase 1                             3
a block sushant lok phase 1                             3
maruti kunj                                             3
ambience island                                         2
west rajiv nagar                                        2
hira nagar                                              2
manohar nagar                                           2
nars                                                    2
bhawani enclave                                         2
rosewood                                                2
iffco chowk                                             2
block a surya vihar                                     2
new basti                                               2
mohan nagar                                             2
sheetla colony                                          2
pratap nagar                                            2
new palam vihar phase 2                                 2
faridabad road                                          2
shankar vihar                                           2
bissar                                                  2
rajiv chowk                                             2
surat nagar                                             2
lajpat nagar                                            2
mayfield garden                                         2
shanti nagar                                            2
surat nagar phase 2                                     2
new palam vihar phase 1                                 2
golf course ext road                                    2
, delhi ncr                                             2
sohna  road                                             2
acharya puri                                            2
sispal vihar                                            2
samaspur                                                2
golf course road                                        2
daulatabad                                              2
farukhnagar                                             2
sushant lok                                             2
gopal nagar, garhi ghasita, sonipat                     1
block h ashok vihar phase iii extension                 1
garauli kalan                                           1
nirvana country pocket h                                1
sultanpur                                               1
ravi nager basai road                                   1
ansal's palam vihar                                     1
carterpuri village                                      1
kanahi                                                  1
south city                                              1
ats marigold                                            1
sec 3 bhim vihar part 1 bhimgher kheri                  1
park view                                               1
near euro                                               1
jat colony,fazilpur/taj nagar road                      1
laxmna vihar, phase 2                                   1
near khandsa road                                       1
khandsa                                                 1
hno 13 sagar enclave sura                               1
damdma                                                  1
vir nagar                                               1
near nand hospital                                      1
alipur                                                  1
bhimgarh kheri phase 3                                  1
mahalaxmi garden, rajendra place                        1
cyber city                                              1
huda saraswati vihar                                    1
laxman vihar, railway road,                             1
saroop garden rajendra park                             1
new jyoti park                                          1
sadar bazar                                             1
jacobpura near sadar bazar                              1
heritage city                                           1
saraswati enclave                                       1
ram nagar                                               1
ashok vihar phase 3                                     1
v block dlf phase 3                                     1
mahavir pura                                            1
ashok vihar phase i                                     1
sai kunj                                                1
rajiv colony                                            1
shivji park colony                                      1
bhora kalan                                             1
kheri                                                   1
naharpur rupa                                           1
bptp                                                    1
devi lal colony gali no 12  nr omkar public school      1
near pataudi chowk                                      1
g block dlf city phase 1                                1
rattan garden                                           1
om nagar                                                1
pataudi road                                            1
lucknow                                                 1
tekchand nagar                                          1
udyog vihar phase 1                                     1
civil l                                                 1
dhankot                                                 1
begampur khatola                                        1
Name: count, dtype: int64

In [14]:
import os
os.chdir(r'C:\Users\apaks\Desktop\Real Estate Project')

In [15]:
#mapping sectors from dictornay in sector_mapping created using copilot

from artifacts.Data.sector_mapping import sector_mapping

df['sector'] = df['sector'].str.strip().str.replace(sector_mapping)

In [16]:
temp_s = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(temp_s.index)]

In [17]:
df['sector'].value_counts().sort_index()

sector
bhondsi                    4
dwarka expressway          8
gwal pahari               14
imt manesar                4
manesar                    5
new                        4
sector 1                   6
sector 1 imt manesar      14
sector 10                  3
sector 102               113
sector 103                45
sector 104                73
sector 105                23
sector 106                38
sector 107                60
sector 108                59
sector 109                88
sector 10a                 8
sector 11                 14
sector 110                16
sector 110 a               3
sector 111                22
sector 112                24
sector 113                43
sector 12                 31
sector 12a                 4
sector 13                  7
sector 14                 23
sector 15                  6
sector 17                  4
sector 17a                 3
sector 17b                 3
sector 1a imt manesar     10
sector 2                  60
sector 2 extension         8
sector 21                  6
sector 22                 20
sector 23                  8
sector 23a                 5
sector 24                 24
sector 25                 43
sector 26                 50
sector 27                  3
sector 28                 47
sector 3                  47
sector 3 phase 2          13
sector 30                  5
sector 31                 12
sector 33                 23
sector 36                  4
sector 36 sector 47        7
sector 36a                13
sector 37c                53
sector 37d                68
sector 38                 12
sector 39                 12
sector 3a                  4
sector 4                   9
sector 40                  8
sector 41                 11
sector 43                 67
sector 45                  9
sector 46                 13
sector 47                182
sector 47 road            12
sector 48                 56
sector 49                 48
sector 5                  26
sector 50                 69
sector 51                  7
sector 52                 19
sector 53                 14
sector 54                 31
sector 55                  9
sector 56                 57
sector 57                 24
sector 58                  7
sector 59                  8
sector 6                  13
sector 60                 15
sector 61                 42
sector 62                 17
sector 63                 15
sector 63a                18
sector 65                 90
sector 66                 46
sector 67                 48
sector 67a                22
sector 68                 30
sector 69                 94
sector 7                  39
sector 70                 53
sector 70a                54
sector 71                 27
sector 72                 29
sector 73                  3
sector 74                 18
sector 76                 14
sector 77                 29
sector 78                 19
sector 79                 80
sector 8                   8
sector 80                  5
sector 81                 90
sector 82                 42
sector 82a                20
sector 83                 69
sector 84                 51
sector 85                110
sector 86                 67
sector 88a                23
sector 88b                 3
sector 89                 60
sector 89 a                8
sector 9                  13
sector 90                 90
sector 91                 17
sector 92                104
sector 93                 12
sector 95                 57
sector 95a                 9
sector 99                 16
sector 99a                32
sector 9a                 11
sector-33 sector 47       51
subhash nagar              5
Name: count, dtype: int64

In [29]:
df.loc[df['sector'] == 'gwal pahari', 'sector'] = 'sector 2'
df.loc[df['sector'] == 'sector-33 sector 47', 'sector'] = 'sector 47'
df.loc[df['sector'] == 'sector 99a', 'sector'] = 'sector 99'
df.loc[df['sector'] == 'sector 95a', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'sector 89 a', 'sector'] = 'sector 89'
df.loc[df['sector'] == 'sector 88b', 'sector'] = 'sector 88'
df.loc[df['sector'] == 'sector 88a', 'sector'] = 'sector 88a'
df.loc[df['sector'] == 'sector 82a', 'sector'] = 'sector 82'
df.loc[df['sector'] == 'sector 70a', 'sector'] = 'sector 70'
df.loc[df['sector'] == 'sector 67a', 'sector'] = 'sector 67'
df.loc[df['sector'] == 'sector 63a', 'sector'] = 'sector 63'
df.loc[df['sector'] == 'sector 37d', 'sector'] = 'sector 37'
df.loc[df['sector'] == 'sector 37c', 'sector'] = 'sector 37'
df.loc[df['sector'] == 'sector 36a', 'sector'] = 'sector 36'
df.loc[df['sector'] == 'sector 47 road', 'sector'] = 'sector 47'
df.loc[df['sector'] == 'sector 36 sector 47', 'sector'] = 'sector 36'
df.loc[df['sector'] == 'sector 3 phase 2', 'sector'] = 'sector 3'
df.loc[df['sector'] == 'sector 23a', 'sector'] = 'sector 23'
df.loc[df['sector'] == 'sector 2 extension', 'sector'] = 'sector 2'
df.loc[df['sector'] == 'sector 1a imt manesar', 'sector'] = 'sector 1'
df.loc[df['sector'] == 'sector 17a', 'sector'] = 'sector 17'
df.loc[df['sector'] == 'sector 17b', 'sector'] = 'sector 17'
df.loc[df['sector'] == 'sector 12a', 'sector'] = 'sector 12'
df.loc[df['sector'] == 'sector 110 a', 'sector'] = 'sector 110'
df.loc[df['sector'] == 'sector 10a', 'sector'] = 'sector 10'
df.loc[df['sector'] == 'sector 1 imt manesar', 'sector'] = 'sector 1'
df.loc[df['sector'] == 'sector 88a', 'sector'] = 'sector 88'
df.loc[df['sector'] == 'sector 9a', 'sector'] = 'sector 9'
df.loc[df['sector'] == 'dwarka expressway', 'sector'] = 'sector 104'
df.loc[df['sector'] == 'imt manesar', 'sector'] = 'sector 1'
df.loc[df['sector'] == 'subhash nagar', 'sector'] = 'sector 8'

In [30]:
df['sector'].value_counts().sort_index()

sector
bhondsi         4
manesar         5
new             4
sector 1       34
sector 10      11
sector 102    113
sector 103     45
sector 104     81
sector 105     23
sector 106     38
sector 107     60
sector 108     59
sector 109     88
sector 11      14
sector 110     19
sector 111     22
sector 112     24
sector 113     43
sector 12      35
sector 13       7
sector 14      23
sector 15       6
sector 17      10
sector 2       82
sector 21       6
sector 22      20
sector 23      13
sector 24      24
sector 25      43
sector 26      50
sector 27       3
sector 28      47
sector 3       60
sector 30       5
sector 31      12
sector 33      23
sector 36      24
sector 37     121
sector 38      12
sector 39      12
sector 3a       4
sector 4        9
sector 40       8
sector 41      11
sector 43      67
sector 45       9
sector 46      13
sector 47     245
sector 48      56
sector 49      48
sector 5       26
sector 50      69
sector 51       7
sector 52      19
sector 53      14
sector 54      31
sector 55       9
sector 56      57
sector 57      24
sector 58       7
sector 59       8
sector 6       13
sector 60      15
sector 61      42
sector 62      17
sector 63      33
sector 65      90
sector 66      46
sector 67      70
sector 68      30
sector 69      94
sector 7       39
sector 70     107
sector 71      27
sector 72      29
sector 73       3
sector 74      18
sector 76      14
sector 77      29
sector 78      19
sector 79      80
sector 8       13
sector 80       5
sector 81      90
sector 82      62
sector 83      69
sector 84      51
sector 85     110
sector 86      67
sector 88      26
sector 89      68
sector 9       24
sector 90      90
sector 91      17
sector 92     104
sector 93      12
sector 95      66
sector 99      48
Name: count, dtype: int64

In [35]:
df = df[df['sector'].str.strip().str.contains('sector')]

In [38]:
df.shape

(3790, 21)

In [39]:
# drop unnecessary columns

df.drop(columns = ['property_name', 'address', 'rating', 'description'], inplace = True)

In [40]:
df.head()

,property_type,society,sector,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,house,independent,sector 105,0.60,11102.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),8,4,3,not available,3.0,West,0 to 1 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Bhar...","['9 Fan', '17 Light', 'No AC', 'No Bed', 'No C...","['Private Garden / Terrace', 'Park']"
1,flat,vatika gurgaon,sector 83,1.18,6801.0,1735.04,Super Built up area 1735(161.19 sq.m.)Carpet a...,3,3,2,not available,14.0,north,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M..."
2,flat,emaar digihomes,sector 62,4.00,14871.0,2689.8,Super Built up area 2588.79(240.51 sq.m.),3,3,3,servant room,18.0,north,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...","['6 Fan', '7 Light', '8 AC', '1 Modular Kitche...","['High Ceiling Height', 'Maintenance Staff', '..."
3,flat,ss the leaf,sector 85,1.10,6318.0,1741.06,Super Built up area 1741(161.74 sq.m.)Carpet a...,2,2,3+,store room,3.0,south-east,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'..."
4,flat,tarc maceo,sector 91,0.89,6339.0,1404.01,Super Built up area 1404(130.44 sq.m.)Carpet a...,2,2,3+,others,9.0,east,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...","['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ..."

In [41]:
df.to_csv(r'artifacts\Data\gurgaon_properties_cleaned_v1.csv')