In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
import os
os.chdir(r'C:\Users\apaks\Desktop\Real Estate Project')

In [4]:
df = pd.read_csv(r'artifacts\Data\flats.csv')

In [5]:
# sample
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1110,2 BHK Flat in Sector 82 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Vatika The Seven Lamps3.8 ★,85.5 Lac,"₹ 5,979/sq.ft.",Super Built up area 1430(132.85 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 82 Gurgaon, Gurgaon, Haryana",9th of 16 Floors,North-East,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2bhk study, 1430 sq. Ft., east...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of...",G69160024
2802,1 BHK Flat in Palam Vihar Extension,https://www.99acres.com/1-bhk-bedroom-apartmen...,Palam Vihar Extension West Zone RWA,20 Lac,"₹ 4,000/sq.ft.",Carpet area: 500 (46.45 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,Others,"Palam Vihar Extension, Gurgaon, Haryana",1st of 4 Floors,NaN,5 to 10 Year Old,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","It's near to main road, 24hrs boring water,","['1 Bed', '1 Wardrobe', '1 Fan', '1 Geyser', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",V62809262
2919,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,GLS Arawali Homes3.8 ★,35 Lac,"₹ 6,076/sq.ft.",Super Built up area 576(53.51 sq.m.)Carpet are...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sohna, Gurgaon, Haryana",11st of 13 Floors,NaN,1 to 5 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...","Situated in sohna, gurgaon, gls arawali homes ...","['3 Fan', '1 Exhaust Fan', '8 Light', '1 AC', ...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area5 out of 5...",C65443558
1417,4 BHK Flat in Sector 82A Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Primus3.9 ★,2.7 Crore,"₹ 10,481/sq.ft.",Super Built up area 2576(239.32 sq.m.)Carpet a...,4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"117, Sector 82A Gurgaon, Gurgaon, Haryana",18th of 32 Floors,East,5 to 10 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...",Located in the popular residential address of ...,NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area5 out of 5', 'Construction4.5 out ...",X68655328
656,3 BHK Flat in Sector 65 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,M3M Golfestate4.4 ★,5.3 Crore,"₹ 24,211/sq.ft.",Super Built up area 2850(264.77 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"Sector 65 Gurgaon, Gurgaon, Haryana",38th of 40 Floors,North-East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",M3m very luxury society on road,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geys...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of...",Y69968948

In [6]:
# shape
df.shape

(3017, 20)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   str
 1   link             3017 non-null   str
 2   society          3016 non-null   str
 3   price            3007 non-null   str
 4   area             3004 non-null   str
 5   areaWithType     3008 non-null   str
 6   bedRoom          3008 non-null   str
 7   bathroom         3008 non-null   str
 8   balcony          3008 non-null   str
 9   additionalRoom   1694 non-null   str
 10  address          3002 non-null   str
 11  floorNum         3006 non-null   str
 12  facing           2127 non-null   str
 13  agePossession    3007 non-null   str
 14  nearbyLocations  2913 non-null   str
 15  description      3008 non-null   str
 16  furnishDetails   2203 non-null   str
 17  features         2594 non-null   str
 18  rating           2676 non-null   str
 19  property_id      3008 non-null   str
dtypes: str(20)
memory usage: 471.5 KB

In [8]:
# missing values in each column
df.isna().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

some of the columns have a very high missing values like additional

In [9]:
# duplicate rows 
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='str')

In [11]:
# drop useless columns like link and property_id
df.drop(columns = ['link', 'property_id'], inplace=True)

In [12]:
# rename area column to price_per_sqft
df.rename(columns={'area': 'price_per_sqft'}, inplace = True)

### Society

In [13]:
df['society'].nunique()

638

In [14]:
df['society'].sort_values()

1074                                                    .
65                                       4S Aradhya Homes
2178                                    511 sarahah tower
2388                                  AFNHB Jalvayu Vihar
418                              AFNHB Jalvayu Vihar3.7 ★
80                               AFNHB Jalvayu Vihar3.7 ★
363                              AFNHB Jalvayu Vihar3.7 ★
342                                  AIPL Club Residences
1282                                 AIPL Club Residences
2134                                 AIPL Club Residences
2042                                      AIPL Joy Square
1751                         AIPL The Peaceful Homes3.9 ★
572                          AIPL The Peaceful Homes3.9 ★
1643                         AIPL The Peaceful Homes3.9 ★
1089                         AIPL The Peaceful Homes3.9 ★
874                          AIPL The Peaceful Homes3.9 ★
1675                         AIPL The Peaceful Homes3.9 ★
587                          AIPL The Peaceful Homes3.9 ★
1047                         AIPL The Peaceful Homes3.9 ★
1579                         AIPL The Peaceful Homes3.9 ★
196                                   AIPL Zen Residences
2196                                  AIPL Zen Residences
2353                                  AIPL Zen Residences
1570                                  AIPL Zen Residences
2056                                  AIPL Zen Residences
184                                   AIPL Zen Residences
1184                                  AIPL Zen Residences
2962                                   ANSALS DUPLEX FLAT
693                                            ATS Kocoon
706                                            ATS Kocoon
831                                            ATS Kocoon
811                                            ATS Kocoon
629                                            ATS Kocoon
1470                                           ATS Kocoon
1387                                           ATS Kocoon
1492                                           ATS Kocoon
1843                                           ATS Kocoon
858                                            ATS Kocoon
890                                       ATS Kocoon4.2 ★
1343                                      ATS Kocoon4.2 ★
1664                                      ATS Kocoon4.2 ★
2195                                         ATS Marigold
2271                                         ATS Marigold
2211                                         ATS Marigold
2065                                         ATS Marigold
2049                                         ATS Marigold
1844                                  ATS Tourmaline3.9 ★
2783                                  ATS Tourmaline3.9 ★
1517                                  ATS Tourmaline3.9 ★
1518                                  ATS Tourmaline3.9 ★
1884                                  ATS Tourmaline3.9 ★
955                                   ATS Tourmaline3.9 ★
1513                                  ATS Tourmaline3.9 ★
631                                   ATS Tourmaline3.9 ★
2600                                  ATS Tourmaline3.9 ★
821                                   ATS Tourmaline3.9 ★
1041                                  ATS Tourmaline3.9 ★
820                                   ATS Tourmaline3.9 ★
819                                   ATS Tourmaline3.9 ★
2469                                  ATS Tourmaline3.9 ★
888                                   ATS Tourmaline3.9 ★
1514                                  ATS Tourmaline3.9 ★
1015                                  ATS Tourmaline3.9 ★
439                                   ATS Tourmaline3.9 ★
1665                                     ATS Triumph3.9 ★
2657                                     ATS Triumph3.9 ★
7                                        ATS Triumph3.9 ★
1702                                     ATS Triumph3.9 ★
1701                                     ATS Triumph3.9 ★
1966                                     ATS Triumph3.9 ★
711                                      ATS Triumph3.9 ★
1321                                     ATS Triumph3.9 ★
1477                                     ATS Triumph3.9 ★
1486                                     ATS Triumph3.9 ★
923                                      ATS Triumph3.9 ★
710                                      ATS Triumph3.9 ★
2750                                     ATS Triumph3.9 ★
897                                      ATS Triumph3.9 ★
718                                      ATS Triumph3.9 ★
894                                      ATS Triumph3.9 ★
937                                      ATS Triumph3.9 ★
2540                                     ATS Triumph3.9 ★
934                                      ATS Triumph3.9 ★
1316                                     ATS Triumph3.9 ★
892                                      ATS Triumph3.9 ★
1476                                     ATS Triumph3.9 ★
2612                                  AVL 36 Gurgaon3.7 ★
2066                                  AVL 36 Gurgaon3.7 ★
2489                                  AVL 36 Gurgaon3.7 ★
2825                                  AVL 36 Gurgaon3.7 ★
2171                                  AVL 36 Gurgaon3.7 ★
1912                                  AVL 36 Gurgaon3.7 ★
2259                                  AVL 36 Gurgaon3.7 ★
2842                                  AVL 36 Gurgaon3.7 ★
2790                               AWHO Shanti Vihar4.0 ★
1942                               AWHO Shanti Vihar4.0 ★
1932                               AWHO Sispal Vihar4.0 ★
166                                        Aardhya homesh
2369                                  Aashirwad Residency
158                         Abhinav Group Housing Society
2351                                      Ace Palm Floors
2893                                  Adani Aangan Arcade
2427                                  Adani Aangan Arcade
33                                    Adani Aangan Arcade
2428                                Adani Aangan Galleria
2017                                Adani Aangan Galleria
2001                          Adani Brahma Samsara Vilasa
2085                          Adani Brahma Samsara Vilasa
2140                          Adani Brahma Samsara Vilasa
2201                          Adani Brahma Samsara Vilasa
2328                          Adani Brahma Samsara Vilasa
1583                         Adani M2K Oyster Grande3.9 ★
1429                         Adani M2K Oyster Grande3.9 ★
1594                         Adani M2K Oyster Grande3.9 ★
510                          Adani M2K Oyster Grande3.9 ★
1099                         Adani M2K Oyster Grande3.9 ★
786                          Adani M2K Oyster Grande3.9 ★
627                          Adani M2K Oyster Grande3.9 ★
1392                         Adani M2K Oyster Grande3.9 ★
1393                         Adani M2K Oyster Grande3.9 ★
1671                         Adani M2K Oyster Grande3.9 ★
369                          Adani M2K Oyster Grande3.9 ★
1670                                  Adani Oyster Greens
2263                                         Adarsh nagar
2948                                     Aditya Apartment
2075                                  Aipl Peaceful Homes
224                                          Allure Homes
1319                        Alpha Corp GurgaonOne 844.0 ★
753                         Alpha Corp GurgaonOne 844.0 ★
635                         Alpha Corp GurgaonOne 844.0 ★
984                         Alpha Corp GurgaonOne 844.0 ★
993                         Alpha Corp GurgaonOne 844.0 ★
528                         Alpha Corp GurgaonOne 844.0 ★
664                         Alpha Corp GurgaonOne 844.0 ★
2421                        Alpha Corp GurgaonOne 844.0 ★
776                         Alpha Corp GurgaonOne 844.0 ★
1079                        Alpha Corp GurgaonOne 844.0 ★
775                         Alpha Corp GurgaonOne 844.0 ★
2570                                   Ambience Caitriona
2680                                   Ambience Caitriona
2346                                   Ambience Creacions
1028                                   Ambience Creacions
473                                    Ambience Creacions
655                                    Ambience Creacions
2756                                   Ambience Creacions
2782                                   Ambience Creacions
573                                    Ambience Creacions
2943                                   Ambience Creacions
2786                                   Ambience Creacions
98                                     Ambience Creacions
366                                    Ambience Creacions
652                                    Ambience Creacions
1029                                   Ambience Creacions
1032                                   Ambience Creacions
1027                                   Ambience Creacions
2805                                   Ambience Creacions
1030                                   Ambience Creacions
2345                                   Ambience Creacions
608                                  Ambience Lagoon3.9 ★
385                                  Ambience Lagoon3.9 ★
3015                                 Ambience Lagoon3.9 ★
84                                        Anamika Enclave
495                            Ansal API Celebrity Suites
944                            Ansal API Celebrity Suites
1943                               Ansal API Esencia3.7 ★
2564                               Ansal API Esencia3.7 ★
1920                        Ansal API Sushant Estate4.1 ★
2992                                        Ansal Estella
2917                             Ansal Harmony Homes3.7 ★
2292                                      Ansal Height 86
2794                                     Ansal Heights 86
332                                      Ansal Heights 86
2445                                     Ansal Heights 86
3012                                     Ansal Heights 86
2571                                     Ansal Heights 86
2162                                     Ansal Heights 86
2681                                     Ansal Heights 86
2407                                     Ansal Heights 86
1978                                     Ansal Heights 86
2059                                     Ansal Heights 86
305                                      Ansal Heights 86
2951                                     Ansal Heights 86
2872                                     Ansal Heights 86
2856                                     Ansal Heights 86
132                                      Ansal Heights 86
759                                    Ansal Heights3.2 ★
194                                    Ansal Heights3.2 ★
733                           Ansal Housing Highland Park
2957                          Ansal Housing Highland Park
2720                          Ansal Housing Highland Park
119                           Ansal Housing Highland Park
270                           Ansal Housing Highland Park
2735                          Ansal Housing Highland Park
622                           Ansal Housing Highland Park
789                                  Ansal Maple Crescent
761                              Ansal Maple Heights3.7 ★
2231                                          Ansal Plaza
40                                   Ansal Sushant Lok CI
2301                              Ansal Sushant Residency
2354                             Ansal Valley View Estate
2968                                   Ansals API Esencia
2765                                 Ansals Highland Park
2289                                       Antriksh Green
1792                                Antriksh Heights3.7 ★
1732                                Antriksh Heights3.7 ★
2695                                Antriksh Heights3.7 ★
2587                                Antriksh Heights3.7 ★
549                                 Antriksh Heights3.7 ★
1745                                Antriksh Heights3.7 ★
1791                                Antriksh Heights3.7 ★
1785                                Antriksh Heights3.7 ★
550                                 Antriksh Heights3.7 ★
422                                 Antriksh Heights3.7 ★
1721                                Antriksh Heights3.7 ★
1733                                Antriksh Heights3.7 ★
1717                                Antriksh Heights3.7 ★
1734                                Antriksh Heights3.7 ★
1720                                Antriksh Heights3.7 ★
1744                                Antriksh Heights3.7 ★
1746                                Antriksh Heights3.7 ★
2449                                Antriksh Heights3.7 ★
1783                                Antriksh Heights3.7 ★
2510                                            Apartment
2629                                            Apartment
1970                                       Apex Our Homes
1422                                       Apex Our Homes
1421                                       Apex Our Homes
29                                          Apex builders
2153                                         Apna Enclave
1                                            Apna Enclave
2953                                         Apna Enclave
2928                                         Apna Enclave
2836                                         Apna Enclave
2163                                    Aqua Front Towers
2112                                    Aqua Front Towers
2712                                      Ardee City3.8 ★
130                                       Ardee City3.8 ★
2299                                        Ashiana Anmol
2702                                        Ashiana Anmol
163                                    Ashiana Anmol3.5 ★
2241                                   Ashiana Anmol3.5 ★
2248                                   Ashiana Anmol3.5 ★
2675                                   Ashiana Anmol3.5 ★
2562                                   Ashiana Anmol3.5 ★
1905                                    Ashiana Apartment
41                                       Ashiana Mulberry
1129                                     Ashiana Mulberry
1130                                     Ashiana Mulberry
2871                                     Ashiana Mulberry
2348                                     Ashiana Mulberry
2007                                     Ashiana Mulberry
2711                                  Ashok vihar phase 2
2308                                     Ashray Apartment
169                                        Assotech Blith
2691                                       Assotech Blith
202                                        Assotech Blith
2901                                       Assotech Blith
2583                                       Assotech Blith
266                                        Assotech Blith
2927                                       Assotech Blith
2718                                       Assotech Blith
2837                                   BPTP Amstoria3.8 ★
1353                                   BPTP Amstoria3.8 ★
1190                            BPTP Astaire Gardens3.7 ★
1191                            BPTP Astaire Gardens3.7 ★
1042                            BPTP Astaire Gardens3.7 ★
1676                            BPTP Astaire Gardens3.7 ★
2076                            BPTP Astaire Gardens3.7 ★
1987                            BPTP Astaire Gardens3.7 ★
67                            BPTP Freedom Park Life4.0 ★
1962                          BPTP Freedom Park Life4.0 ★
851                              BPTP Mansions Park Prime
1166                             BPTP Mansions Park Prime
2208                           BPTP Park Generations3.7 ★
2827                                        BPTP Pedestal
262                                         BPTP Pedestal
845                                       BPTP Terra3.8 ★
1428                                      BPTP Terra3.8 ★
1427                                      BPTP Terra3.8 ★
785                                       BPTP Terra3.8 ★
413                                       BPTP Terra3.8 ★
1625                                      BPTP Terra3.8 ★
1623                                      BPTP Terra3.8 ★
601                                       BPTP Terra3.8 ★
1256                                      BPTP Terra3.8 ★
1255                                      BPTP Terra3.8 ★
399                                       BPTP Terra3.8 ★
1040                                      BPTP Terra3.8 ★
1818                                      BPTP Terra3.8 ★
1817                                      BPTP Terra3.8 ★
1626                                      BPTP Terra3.8 ★
1816                                      BPTP Terra3.8 ★
1038                                      BPTP Terra3.8 ★
1251                                      BPTP Terra3.8 ★
155                                       BPTP Terra3.8 ★
1252                                      BPTP Terra3.8 ★
1253                                      BPTP Terra3.8 ★
1425                                      BPTP Terra3.8 ★
1039                                      BPTP Terra3.8 ★
1254                                      BPTP Terra3.8 ★
1426                                      BPTP Terra3.8 ★
2217                                              BSF CHS
283                                     Baani City Center
2193                          Belgravia Resort Residences
1018                                       Bestech Altura
21                                         Bestech Altura
378                                        Bestech Altura
2261                                       Bestech Altura
2291                                       Bestech Altura
1904                                       Bestech Altura
2113                                       Bestech Altura
2273                                       Bestech Altura
2981                             Bestech Park View Ananda
1547                        Bestech Park View Ananda4.2 ★
1875                        Bestech Park View Ananda4.2 ★
1874                        Bestech Park View Ananda4.2 ★
1956                        Bestech Park View Ananda4.2 ★
1873                        Bestech Park View Ananda4.2 ★
1774                        Bestech Park View Ananda4.2 ★
1740                        Bestech Park View Ananda4.2 ★
1716                        Bestech Park View Ananda4.2 ★
553                         Bestech Park View Ananda4.2 ★
463                         Bestech Park View Ananda4.2 ★
1416                        Bestech Park View Ananda4.2 ★
1781                        Bestech Park View Ananda4.2 ★
2029                        Bestech Park View Ananda4.2 ★
678                         Bestech Park View City 23.9 ★
853                         Bestech Park View City 23.9 ★
78                          Bestech Park View City 23.9 ★
1504                          Bestech Park View City4.1 ★
1026                          Bestech Park View City4.1 ★
1046                          Bestech Park View City4.1 ★
345                           Bestech Park View City4.1 ★
768                           Bestech Park View City4.1 ★
623                           Bestech Park View City4.1 ★
2487                     Bestech Park View Grand Spa4.3 ★
1466                     Bestech Park View Grand Spa4.3 ★
565                      Bestech Park View Grand Spa4.3 ★
1820                     Bestech Park View Grand Spa4.3 ★
771                      Bestech Park View Grand Spa4.3 ★
2611                     Bestech Park View Grand Spa4.3 ★
1546                     Bestech Park View Grand Spa4.3 ★
611                      Bestech Park View Grand Spa4.3 ★
1715                     Bestech Park View Grand Spa4.3 ★

many society names contain rating in the end

In [15]:
#removing rating from society name

import re
df['society'] = df['society'].apply(lambda name : re.sub(r'\d+(\.\d+)?\s?★', '', str(name))).str.strip().str.lower()

In [16]:
df['society'].nunique()

604

### Price columns

In [17]:
df['price'].value_counts().sort_index()

price
1 Crore             46
1.01 Crore           6
1.02 Crore           7
1.04 Crore           3
1.05 Crore          30
1.06 Crore           1
1.07 Crore           6
1.08 Crore          11
1.09 Crore           3
1.1 Crore           61
1.11 Crore           1
1.12 Crore          10
1.13 Crore           6
1.14 Crore           6
1.15 Crore          33
1.16 Crore           6
1.17 Crore           5
1.18 Crore           8
1.19 Crore           7
1.2 Crore           59
1.21 Crore           3
1.22 Crore           4
1.23 Crore           4
1.24 Crore           5
1.25 Crore          79
1.26 Crore           8
1.27 Crore           7
1.28 Crore          10
1.29 Crore           7
1.3 Crore           57
1.31 Crore           4
1.32 Crore          13
1.33 Crore           5
1.34 Crore           6
1.35 Crore          41
1.36 Crore           7
1.37 Crore           4
1.38 Crore          15
1.39 Crore           6
1.4 Crore           60
1.41 Crore           3
1.42 Crore          12
1.43 Crore           5
1.44 Crore           5
1.45 Crore          31
1.46 Crore           2
1.47 Crore           5
1.48 Crore           4
1.49 Crore           6
1.5 Crore           59
1.51 Crore           6
1.52 Crore           4
1.53 Crore           1
1.54 Crore           8
1.55 Crore          40
1.56 Crore           2
1.57 Crore           3
1.58 Crore           4
1.59 Crore           6
1.6 Crore           43
1.62 Crore           5
1.63 Crore           3
1.64 Crore           4
1.65 Crore          38
1.66 Crore           4
1.67 Crore           3
1.68 Crore           9
1.69 Crore           5
1.7 Crore           37
1.71 Crore           4
1.72 Crore           9
1.73 Crore           4
1.74 Crore           1
1.75 Crore          47
1.76 Crore           8
1.77 Crore           4
1.78 Crore          10
1.79 Crore           5
1.8 Crore           37
1.82 Crore           5
1.83 Crore           5
1.84 Crore           1
1.85 Crore          23
1.86 Crore           1
1.87 Crore           2
1.88 Crore           3
1.9 Crore           40
1.91 Crore           5
1.92 Crore           5
1.93 Crore           5
1.95 Crore          12
1.97 Crore           1
1.98 Crore           6
1.99 Crore           7
10 Crore             1
10.75 Crore          1
11 Crore             2
11.25 Crore          1
13.2 Crore           1
14 Crore             2
15 Crore             1
16 Lac               1
17.5 Lac             1
19 Lac               1
2 Crore             51
2.01 Crore           3
2.02 Crore           2
2.03 Crore           3
2.04 Crore           2
2.05 Crore           9
2.06 Crore           1
2.07 Crore           1
2.08 Crore           3
2.09 Crore           4
2.1 Crore           26
2.11 Crore           1
2.12 Crore           5
2.13 Crore           2
2.14 Crore           2
2.15 Crore          14
2.17 Crore           2
2.2 Crore           34
2.21 Crore           1
2.22 Crore           5
2.23 Crore           2
2.24 Crore           3
2.25 Crore          20
2.26 Crore           2
2.28 Crore           3
2.29 Crore           5
2.3 Crore           18
2.32 Crore           1
2.33 Crore           3
2.34 Crore           1
2.35 Crore          23
2.36 Crore           3
2.37 Crore           1
2.38 Crore           1
2.4 Crore           18
2.41 Crore           2
2.44 Crore           1
2.45 Crore          14
2.48 Crore           1
2.49 Crore           1
2.5 Crore           29
2.51 Crore           3
2.52 Crore           2
2.54 Crore           1
2.55 Crore          10
2.57 Crore           2
2.58 Crore           2
2.6 Crore           15
2.61 Crore           1
2.62 Crore           1
2.63 Crore           1
2.64 Crore           1
2.65 Crore          16
2.69 Crore           1
2.7 Crore           13
2.72 Crore           1
2.75 Crore           8
2.77 Crore           1
2.78 Crore           5
2.79 Crore           3
2.8 Crore           12
2.82 Crore           1
2.85 Crore           9
2.86 Crore           1
2.87 Crore           2
2.9 Crore            7
2.91 Crore           2
2.92 Crore           1
2.95 Crore           6
2.96 Crore           1
2.97 Crore           1
2.98 Crore           1
2.99 Crore           2
20 Lac               8
20.5 Lac             1
21 Lac               6
22 Lac               9
23 Lac               1
23.5 Lac             1
24 Lac               5
24.5 Lac             1
25 Lac              11
25.5 Lac             2
26 Lac              10
26.1 Lac             1
26.5 Lac             1
26.9 Lac             1
27 Lac               8
27.1 Lac             2
27.5 Lac             1
27.75 Lac            2
28 Lac              10
28.5 Lac             4
29 Lac               5
29.5 Lac             1
29.8 Lac             1
29.99 Lac            1
3 Crore             22
3.05 Crore           6
3.1 Crore            4
3.15 Crore           3
3.19 Crore           1
3.2 Crore            8
3.21 Crore           2
3.23 Crore           1
3.25 Crore          13
3.29 Crore           2
3.3 Crore            7
3.32 Crore           2
3.35 Crore           6
3.39 Crore           1
3.4 Crore           14
3.45 Crore           9
3.46 Crore           1
3.49 Crore           3
3.5 Crore           19
3.55 Crore           2
3.6 Crore            4
3.63 Crore           1
3.65 Crore           6
3.67 Crore           1
3.7 Crore            7
3.72 Crore           1
3.75 Crore           5
3.78 Crore           1
3.79 Crore           1
3.8 Crore            3
3.83 Crore           1
3.85 Crore           3
3.87 Crore           1
3.9 Crore            6
3.95 Crore           4
3.98 Crore           1
3.99 Crore           1
30 Lac              17
31 Lac               4
31.5 Lac             2
31.75 Lac            1
32 Lac              11
32.5 Lac             1
33 Lac               4
34 Lac               3
35 Lac              23
35.5 Lac             1
36 Lac               9
36.5 Lac             4
37 Lac               6
37.1 Lac             1
37.5 Lac             1
38 Lac              13
39 Lac               7
39.5 Lac             1
4 Crore              9
4.02 Crore           1
4.1 Crore            6
4.16 Crore           1
4.2 Crore            3
4.21 Crore           1
4.25 Crore           8
4.26 Crore           2
4.3 Crore            4
4.4 Crore            1
4.45 Crore           2
4.49 Crore           2
4.5 Crore            5
4.52 Crore           1
4.55 Crore           2
4.6 Crore            2
4.63 Crore           1
4.67 Crore           1
4.7 Crore            2
4.75 Crore           3
4.78 Crore           1
4.79 Crore           1
4.8 Crore            3
4.85 Crore           4
4.86 Crore           1
4.94 Crore           1
4.95 Crore           1
40 Lac              29
40.3 Lac             1
41 Lac               2
41.5 Lac             4
42 Lac              12
42.5 Lac             1
43 Lac               6
44 Lac               1
45 Lac              26
46 Lac               7
47 Lac               3
47.5 Lac             1
48 Lac               8
49 Lac               5
49.5 Lac             1
5 Crore             12
5.15 Crore           1
5.2 Crore            2
5.25 Crore           4
5.3 Crore            1
5.31 Crore           1
5.4 Crore            1
5.49 Crore           1
5.5 Crore            6
5.6 Crore            4
5.7 Crore            2
5.75 Crore           1
5.8 Crore            3
5.9 Crore            4
50 Lac              33
51 Lac               3
52 Lac               3
52.5 Lac             1
52.56 Lac            2
53 Lac               2
53.2 Lac             1
53.5 Lac             2
54 Lac               6
54.8 Lac             1
54.99 Lac            1
55 Lac              20
55.5 Lac             1
55.6 Lac             1
56 Lac               8
56.2 Lac             2
57 Lac               1
58 Lac               4
59 Lac               2
6 Crore              8
6.02 Crore           1
6.1 Crore            1
6.15 Crore           4
6.16 Crore           1
6.2 Crore            2
6.25 Crore           1
6.3 Crore            1
6.44 Crore           1
6.5 Crore            8
6.75 Crore           5
60 Lac              29
61 Lac               1
62 Lac               4
62.5 Lac             1
63.4 Lac             1
64 Lac               5
64.45 Lac            1
64.5 Lac             3
65 Lac              25
65.5 Lac             1
66 Lac               5
66.99 Lac            1
67 Lac               4
68 Lac               5
68.5 Lac             1
68.85 Lac            1
69 Lac               3
7 Crore              4
7.15 Crore           1
7.4 Crore            1
7.5 Crore            2
7.52 Crore           1
7.56 Crore           1
7.8 Crore            1
7.9 Crore            1
70 Lac              21
70.85 Lac            1
71 Lac               2
71.2 Lac             1
71.5 Lac             6
72 Lac               7
72.5 Lac             3
73 Lac               4
73.53 Lac            1
74 Lac               4
75 Lac              38
77.5 Lac             2
78 Lac              13
79 Lac               7
79.9 Lac             1
8 Crore              2
8.25 Crore           1
8.35 Crore           1
8.44 Crore           1
8.5 Crore            2
80 Lac              36
80.5 Lac             1
81 Lac               1
82 Lac              13
82.5 Lac             1
83 Lac               3
84 Lac               3
85 Lac              31
85.5 Lac             1
85.75 Lac            1
86 Lac               8
86.92 Lac            1
86.99 Lac            1
87 Lac              10
87.5 Lac             2
87.99 Lac            1
88 Lac              11
88.4 Lac             1
88.5 Lac             2
89 Lac               4
89.5 Lac             1
89.77 Lac            1
9 Crore              1
9.14 Crore           1
9.2 Crore            1
9.3 Crore            1
9.95 Crore           1
90 Lac              58
90.5 Lac             1
91 Lac               3
92 Lac              13
93 Lac               5
93.75 Lac            1
94 Lac               3
94.25 Lac            1
94.5 Lac             1
94.99 Lac            1
95 Lac              53
95.5 Lac             1
95.75 Lac            1
96 Lac               6
96.07 Lac            1
97 Lac               7
97.04 Lac            1
97.5 Lac             1
98 Lac               8
98.1 Lac             1
98.5 Lac             2
98.88 Lac            1
99 Lac               9
99.5 Lac             1
Price on Request    11
Name: count, dtype: int64

Price on Request    11 --> remove these rows

In [18]:
temp_df = df[df['price'] == 'Price on Request']

In [19]:
temp_df.index

Index([25, 1644, 1972, 2054, 2357, 2522, 2549, 2640, 2959, 2972, 2973], dtype='int64')

In [20]:
# dropping the rows where price is not available
df = df.drop(index = temp_df.index)

In [21]:
df.shape

(3006, 18)

remove 'Lac' and 'Crore' convert them to crores

In [22]:
#remove 'Lac'

mask = df['price'].str.contains('Lac', na = False)
df['price'] = df['price'].astype('object')
df.loc[mask, 'price'] = df.loc[mask, 'price'].str.split().str.get(0).astype(float) * 0.01

In [23]:
# remove 'Crore'

mask = df['price'].str.contains('Crore', na = False)
df.loc[mask, 'price'] = df.loc[mask, 'price'].str.split().str.get(0)

In [24]:
df['price'] = df['price'].astype(float).round(2)

In [25]:
df.rename(columns={'price': 'price_in_cr'}, inplace= True)

In [26]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

### price_per_sqft column

In [27]:
# extract numbers from the sqft columns and convert them to 'Int64'. Chose 'Int64' because it works with missing values

df['price_per_sqft'] = df['price_per_sqft'].str.extract(r'([\d,]+)')[0].str.replace(',', '').str.strip().astype('Int64')

In [28]:
df['price_per_sqft'].isna().sum()

np.int64(2)

In [29]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

### AreaWithType column

In [30]:
df['areaWithType'].value_counts()

areaWithType
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Carpet area: 1350 (125.42 sq.m.)                                                                                                 9
Carpet area: 1450 (134.71 sq.m.)                                                                                                 9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Carpet area: 900 (83.61 sq.m.)                                                                                                   8
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Super Built up area 2100(195.1 sq.m.)                                                                                            7
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Carpet area: 1300 (120.77 sq.m.)                                                                                                 7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Carpet area: 2300 (213.68 sq.m.)                                                                                                 7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Super Built up area 1200(111.48 sq.m.)                                                                                           7
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 1750(162.58 sq.m.)                                                                                           6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 1000(92.9 sq.m.)                                                                                             5
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Carpet area: 850 (78.97 sq.m.)                                                                                                   5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Carpet area: 1050 (97.55 sq.m.)                                                                                                  5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Carpet area: 1225 (113.81 sq.m.)                                                                                                 4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Carpet area: 800 (74.32 sq.m.)                                                                                                   4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Super Built up area 2400(222.97 sq.m.)                                                                                           4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Built Up area: 1350 (125.42 sq.m.)                                                                                               4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Carpet area: 650 (60.39 sq.m.)                                                                                                   3
Carpet area: 1075 (99.87 sq.m.)                                                                                                  3
Carpet area: 531 (49.33 sq.m.)                                                                                                   3
Carpet area: 1210 (112.41 sq.m.)                                                                                                 3
Carpet area: 1385 (128.67 sq.m.)                                                                                                 3
Carpet area: 2100 (195.1 sq.m.)                                                                                                  3
Carpet area: 1120 (104.05 sq.m.)                                                                                                 3
Super Built up area 1370(127.28 sq.m.)                                                                                           3
Carpet area: 640 (59.46 sq.m.)                                                                                                   3
Carpet area: 1380 (128.21 sq.m.)                                                                                                 3
Super Built up area 1423(132.2 sq.m.)                                                                                            3
Carpet area: 591 (54.91 sq.m.)                                                                                                   3
Carpet area: 1630 (151.43 sq.m.)                                                                                                 3
Carpet area: 1180 (109.63 sq.m.)                                                                                                 3
Carpet area: 2298 (213.49 sq.m.)                                                                                                 3
Built Up area: 2400 (222.97 sq.m.)                                                                                               3
Carpet area: 710 (65.96 sq.m.)                                                                                                   3
Carpet area: 990 (91.97 sq.m.)                                                                                                   3
Super Built up area 1620(150.5 sq.m.)                                                                                            3
Super Built up area 1295(120.31 sq.m.)                                                                                           3
Built Up area: 1150 (106.84 sq.m.)                                                                                               3
Super Built up area 2905(269.88 sq.m.)                                                                                           3
Built Up area: 1310 (121.7 sq.m.)                                                                                                3
Super Built up area 1095(101.73 sq.m.)                                                                                           3
Built Up area: 1423 (132.2 sq.m.)                                                                                                3
Carpet area: 1750 (162.58 sq.m.)                                                                                                 3
Super Built up area 1630(151.43 sq.m.)                                                                                           3
Carpet area: 745 (69.21 sq.m.)                                                                                                   3

### Bedroom, Bathrooms, Balcony columns

In [31]:
# bedroom column
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).str.strip().astype('Int64')

In [32]:
# all the 9 rows with null values in bedroom have rest of the data missing as well. Therefore removing those rows

df = df[~df['bedRoom'].isna()]
df.shape

(2997, 18)

In [33]:
# bathroom column
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).str.strip().astype('Int64')

In [34]:
df['bathroom'].isnull().sum()

np.int64(0)

In [35]:
# balcony column
df['balcony'] = df['balcony'].str.strip().str.split(' ').str.get(0).str.replace('No', '0')

In [36]:
df['balcony'].isna().sum()

np.int64(0)

In [37]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

### AdditionalRoom Column

In [38]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Pooja Room,Study Room,Others                       2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Store Room,Pooja Room,Servant Room                 1
Study Room,Servant Room,Pooja Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Servant Room,Pooja Room,Store Room                 1
Store Room,Study Room                              1
Study Room,Store Room                              1
Servant Room,Pooja Room,Store Room,Study Room      1
Servant Room,Study Room,Pooja Room                 1
Servant Room,Pooja Room,Study Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [39]:
df['additionalRoom'].isna().sum()
df['additionalRoom'] = df['additionalRoom'].fillna('Not Available').str.lower()

In [40]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

### FloorNum Column

In [41]:
df['floorNum'].value_counts().sort_index()

floorNum
10th   of 10 Floors         12
10th   of 11 Floors          2
10th   of 12 Floors         10
10th   of 13 Floors          8
10th   of 14 Floors         35
10th   of 15 Floors          6
10th   of 16 Floors          3
10th   of 17 Floors          8
10th   of 18 Floors         17
10th   of 19 Floors         18
10th   of 20 Floors          6
10th   of 21 Floors          7
10th   of 22 Floors          2
10th   of 23 Floors          3
10th   of 24 Floors          5
10th   of 25 Floors          5
10th   of 26 Floors         13
10th   of 27 Floors          5
10th   of 28 Floors          3
10th   of 29 Floors          6
10th   of 30 Floors          3
10th   of 32 Floors          2
10th   of 33 Floors          1
10th   of 34 Floors          1
10th   of 39 Floors          1
10th   of 40 Floors          2
10th   of 51 Floors          1
11st   of 11 Floors          7
11st   of 12 Floors          6
11st   of 13 Floors          7
11st   of 14 Floors         23
11st   of 15 Floors          4
11st   of 16 Floors          5
11st   of 17 Floors          4
11st   of 18 Floors         11
11st   of 19 Floors          6
11st   of 20 Floors          4
11st   of 21 Floors          2
11st   of 22 Floors          1
11st   of 23 Floors          2
11st   of 24 Floors          7
11st   of 25 Floors          5
11st   of 26 Floors          7
11st   of 27 Floors          3
11st   of 29 Floors          5
11st   of 30 Floors          5
11st   of 36 Floors          1
12nd   of 12 Floors         17
12nd   of 13 Floors          7
12nd   of 14 Floors         49
12nd   of 15 Floors          7
12nd   of 16 Floors          4
12nd   of 17 Floors          9
12nd   of 18 Floors         10
12nd   of 19 Floors          8
12nd   of 21 Floors          5
12nd   of 22 Floors          6
12nd   of 23 Floors          3
12nd   of 24 Floors          8
12nd   of 25 Floors          2
12nd   of 26 Floors          8
12nd   of 27 Floors          3
12nd   of 28 Floors          1
12nd   of 29 Floors          5
12nd   of 30 Floors          4
12nd   of 32 Floors          1
12nd   of 34 Floors          1
12nd   of 39 Floors          1
12nd   of 40 Floors          1
13rd   of 13 Floors          7
13rd   of 14 Floors          9
13rd   of 15 Floors          3
13rd   of 17 Floors          1
13rd   of 18 Floors          1
13rd   of 19 Floors          4
13rd   of 20 Floors          2
13rd   of 21 Floors          4
13rd   of 22 Floors          1
13rd   of 25 Floors          4
13rd   of 26 Floors          1
13rd   of 30 Floors          2
13rd   of 34 Floors          1
13rd   of 40 Floors          2
13rd   of 47 Floors          1
14th   of 14 Floors         48
14th   of 15 Floors          9
14th   of 16 Floors          5
14th   of 17 Floors          4
14th   of 18 Floors          4
14th   of 19 Floors          9
14th   of 20 Floors          2
14th   of 21 Floors          4
14th   of 22 Floors          1
14th   of 24 Floors          8
14th   of 25 Floors          1
14th   of 26 Floors          4
14th   of 27 Floors          6
14th   of 28 Floors          2
14th   of 29 Floors          5
14th   of 32 Floors          3
14th   of 41 Floors          1
14th   of 51 Floors          1
15th   of 15 Floors          6
15th   of 16 Floors          4
15th   of 17 Floors          2
15th   of 18 Floors          5
15th   of 19 Floors         11
15th   of 20 Floors          3
15th   of 21 Floors          5
15th   of 22 Floors          3
15th   of 23 Floors          4
15th   of 24 Floors          2
15th   of 25 Floors          4
15th   of 26 Floors          4
15th   of 27 Floors          1
15th   of 28 Floors          5
15th   of 29 Floors          9
15th   of 30 Floors          1
15th   of 31 Floors          2
15th   of 32 Floors          4
15th   of 39 Floors          3
15th   of 40 Floors          3
15th   of 45 Floors          2
16th   of 16 Floors          7
16th   of 18 Floors          6
16th   of 19 Floors         11
16th   of 20 Floors          3
16th   of 21 Floors          2
16th   of 22 Floors          1
16th   of 24 Floors          2
16th   of 25 Floors          1
16th   of 26 Floors          5
16th   of 27 Floors          2
16th   of 30 Floors          2
16th   of 31 Floors          1
16th   of 32 Floors          2
16th   of 34 Floors          2
16th   of 35 Floors          1
16th   of 36 Floors          2
16th   of 41 Floors          1
16th   of 45 Floors          1
16th   of 51 Floors          1
17th   of 17 Floors         11
17th   of 18 Floors          4
17th   of 19 Floors          6
17th   of 20 Floors          3
17th   of 21 Floors          1
17th   of 22 Floors          1
17th   of 23 Floors          2
17th   of 24 Floors          4
17th   of 25 Floors          4
17th   of 26 Floors          4
17th   of 28 Floors          1
17th   of 29 Floors          3
17th   of 30 Floors          3
17th   of 31 Floors          1
17th   of 33 Floors          2
17th   of 47 Floors          1
18th   of 18 Floors          3
18th   of 19 Floors          9
18th   of 20 Floors          1
18th   of 21 Floors          2
18th   of 22 Floors          1
18th   of 23 Floors          1
18th   of 24 Floors          2
18th   of 25 Floors          1
18th   of 26 Floors          3
18th   of 29 Floors          5
18th   of 30 Floors          3
18th   of 32 Floors          4
18th   of 35 Floors          1
18th   of 40 Floors          1
18th   of 51 Floors          1
19th   of 19 Floors          6
19th   of 20 Floors          2
19th   of 21 Floors          3
19th   of 22 Floors          1
19th   of 23 Floors          1
19th   of 24 Floors          4
19th   of 26 Floors          1
19th   of 27 Floors          2
19th   of 29 Floors          3
19th   of 30 Floors          3
19th   of 31 Floors          1
19th   of 32 Floors          1
19th   of 39 Floors          1
19th   of 40 Floors          4
19th   of 41 Floors          1
1st   of 1 Floors           23
1st   of 10 Floors           6
1st   of 11 Floors           3
1st   of 12 Floors           5
1st   of 13 Floors           7
1st   of 14 Floors          26
1st   of 15 Floors           5
1st   of 16 Floors           2
1st   of 17 Floors           2
1st   of 18 Floors           4
1st   of 19 Floors           8
1st   of 2 Floors           13
1st   of 20 Floors           2
1st   of 22 Floors           2
1st   of 24 Floors           2
1st   of 25 Floors           3
1st   of 26 Floors          10
1st   of 3 Floors           15
1st   of 30 Floors           2
1st   of 35 Floors           3
1st   of 4 Floors           61
1st   of 44 Floors           1
1st   of 5 Floors            6
1st   of 6 Floors            1
1st   of 7 Floors            5
1st   of 8 Floors            2
1st   of 9 Floors            1
20th   of 20 Floors          4
20th   of 22 Floors          2
20th   of 23 Floors          2
20th   of 24 Floors          1
20th   of 25 Floors          2
20th   of 26 Floors          4
20th   of 28 Floors          3
20th   of 29 Floors          1
20th   of 30 Floors          1
20th   of 32 Floors          1
20th   of 34 Floors          1
20th   of 40 Floors          1
20th   of 43 Floors          1
20th   of 47 Floors          1
21st   of 22 Floors          3
21st   of 23 Floors          1
21st   of 24 Floors          3
21st   of 26 Floors          1
21st   of 27 Floors          2
21st   of 28 Floors          1
21st   of 29 Floors          1
21st   of 36 Floors          1
21st   of 41 Floors          1
21st   of 51 Floors          1
22nd   of 23 Floors          1
22nd   of 24 Floors          4
22nd   of 25 Floors          2
22nd   of 26 Floors          1
22nd   of 28 Floors          1
22nd   of 30 Floors          4
22nd   of 40 Floors          1
23rd   of 23 Floors          3
23rd   of 24 Floors          1
23rd   of 26 Floors          4
23rd   of 28 Floors          1
23rd   of 29 Floors          2
23rd   of 34 Floors          2
23rd   of 36 Floors          1
23rd   of 40 Floors          1
24th   of 24 Floors          3
24th   of 27 Floors          1
24th   of 30 Floors          2
24th   of 31 Floors          1
24th   of 32 Floors          1
24th   of 36 Floors          1
24th   of 39 Floors          1
24th   of 51 Floors          1
25th   of 25 Floors          4
25th   of 29 Floors          2
25th   of 30 Floors          2
25th   of 36 Floors          1
26th   of 30 Floors          3
26th   of 34 Floors          1
26th   of 47 Floors          1
27th   of 27 Floors          3
27th   of 29 Floors          2
27th   of 30 Floors          1
27th   of 48 Floors          1
28th   of 28 Floors          1
28th   of 29 Floors          1
28th   of 30 Floors          2
29th   of 29 Floors          1
29th   of 31 Floors          1
29th   of 39 Floors          1
2nd   of 10 Floors           7
2nd   of 11 Floors           4
2nd   of 12 Floors          15
2nd   of 13 Floors           7
2nd   of 14 Floors          21
2nd   of 15 Floors           8
2nd   of 16 Floors           4
2nd   of 17 Floors           7
2nd   of 18 Floors           2
2nd   of 19 Floors          10
2nd   of 2 Floors           26
2nd   of 20 Floors           6
2nd   of 21 Floors           2
2nd   of 22 Floors           3
2nd   of 24 Floors           2
2nd   of 25 Floors           2
2nd   of 26 Floors           3
2nd   of 27 Floors           1
2nd   of 28 Floors           2
2nd   of 3 Floors           22
2nd   of 32 Floors           2
2nd   of 34 Floors           1
2nd   of 36 Floors           1
2nd   of 4 Floors           74
2nd   of 40 Floors           2
2nd   of 5 Floors            8
2nd   of 6 Floors            2
2nd   of 7 Floors            2
2nd   of 8 Floors            8
2nd   of 9 Floors            4
30th   of 32 Floors          3
30th   of 34 Floors          1
30th   of 40 Floors          1
31st   of 32 Floors          3
31st   of 40 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
33rd   of 33 Floors          1
33rd   of 42 Floors          1
33rd   of 48 Floors          1
34th   of 34 Floors          1
34th   of 42 Floors          1
35th   of 35 Floors          1
35th   of 51 Floors          1
38th   of 40 Floors          1
39th   of 40 Floors          2
3rd   of 10 Floors           4
3rd   of 11 Floors           4
3rd   of 12 Floors           9
3rd   of 13 Floors          13
3rd   of 14 Floors          24
3rd   of 15 Floors           8
3rd   of 16 Floors           3
3rd   of 17 Floors           4
3rd   of 18 Floors          16
3rd   of 19 Floors           8
3rd   of 20 Floors           5
3rd   of 22 Floors           4
3rd   of 24 Floors           2
3rd   of 25 Floors           6
3rd   of 26 Floors           3
3rd   of 27 Floors           2
3rd   of 28 Floors           1
3rd   of 29 Floors           2
3rd   of 3 Floors           26
3rd   of 30 Floors           1
3rd   of 31 Floors           1
3rd   of 32 Floors           2
3rd   of 33 Floors           2
3rd   of 36 Floors           1
3rd   of 4 Floors           71
3rd   of 40 Floors           1
3rd   of 5 Floors           10
3rd   of 6 Floors            1
3rd   of 7 Floors            1
3rd   of 8 Floors            3
3rd   of 9 Floors           10
40th   of 40 Floors          2
43   of 47 Floors            2
44   of 47 Floors            1
45   of 47 Floors            1
4th   of 10 Floors          11
4th   of 11 Floors           2
4th   of 12 Floors          10
4th   of 13 Floors          11
4th   of 14 Floors          28
4th   of 15 Floors          10
4th   of 16 Floors           3
4th   of 17 Floors           6
4th   of 18 Floors           6
4th   of 19 Floors           7
4th   of 20 Floors           3
4th   of 21 Floors           3
4th   of 22 Floors           5
4th   of 25 Floors           1
4th   of 26 Floors           8
4th   of 27 Floors           5
4th   of 28 Floors           1
4th   of 29 Floors           3
4th   of 34 Floors           2
4th   of 39 Floors           1
4th   of 4 Floors           62
4th   of 40 Floors           1
4th   of 5 Floors            2
4th   of 6 Floors            1
4th   of 7 Floors            2
4th   of 8 Floors            4
4th   of 9 Floors            5
5th   of 10 Floors           6
5th   of 11 Floors           2
5th   of 12 Floors          22
5th   of 13 Floors           8
5th   of 14 Floors          24
5th   of 15 Floors          16
5th   of 16 Floors           4
5th   of 17 Floors           3
5th   of 18 Floors           9
5th   of 19 Floors           5
5th   of 20 Floors           7
5th   of 21 Floors           1
5th   of 22 Floors           6
5th   of 23 Floors           4
5th   of 24 Floors           4
5th   of 25 Floors           6
5th   of 26 Floors           3
5th   of 27 Floors           1
5th   of 29 Floors           7
5th   of 30 Floors           3
5th   of 32 Floors           1
5th   of 34 Floors           1
5th   of 35 Floors           1
5th   of 36 Floors           1
5th   of 5 Floors           13
5th   of 6 Floors            1
5th   of 8 Floors            5
5th   of 9 Floors            8
6th   of 10 Floors          13
6th   of 11 Floors           5
6th   of 12 Floors          15
6th   of 13 Floors          10
6th   of 14 Floors          27
6th   of 15 Floors          12
6th   of 16 Floors           9
6th   of 17 Floors           5
6th   of 18 Floors          18
6th   of 19 Floors          14
6th   of 20 Floors           5
6th   of 21 Floors           3
6th   of 22 Floors           3
6th   of 23 Floors           3
6th   of 24 Floors           3
6th   of 25 Floors           1
6th   of 26 Floors           9
6th   of 29 Floors           3
6th   of 30 Floors           4
6th   of 31 Floors           2
6th   of 6 Floors           11
6th   of 7 Floors            1
6th   of 8 Floors            3
6th   of 9 Floors            6
7th   of 10 Floors           4
7th   of 11 Floors           4
7th   of 12 Floors           9
7th   of 13 Floors          10
7th   of 14 Floors          35
7th   of 15 Floors          17
7th   of 16 Floors           2
7th   of 17 Floors           9
7th   of 18 Floors          17
7th   of 19 Floors           7
7th   of 20 Floors           6
7th   of 21 Floors          10
7th   of 22 Floors           2
7th   of 23 Floors           3
7th   of 24 Floors           4
7th   of 25 Floors           1
7th   of 26 Floors          10
7th   of 27 Floors           5
7th   of 28 Floors           1
7th   of 29 Floors           2
7th   of 30 Floors           2
7th   of 32 Floors           1
7th   of 34 Floors           1
7th   of 36 Floors           2
7th   of 40 Floors           1
7th   of 42 Floors           1
7th   of 7 Floors           13
7th   of 8 Floors            5
7th   of 9 Floors            4
8th   of 10 Floors           7
8th   of 11 Floors           3
8th   of 12 Floors          11
8th   of 13 Floors           8
8th   of 14 Floors          34
8th   of 15 Floors           9
8th   of 16 Floors           4
8th   of 17 Floors           3
8th   of 18 Floors          20
8th   of 19 Floors          24
8th   of 20 Floors           4
8th   of 21 Floors           7
8th   of 22 Floors           9
8th   of 23 Floors           2
8th   of 24 Floors           8
8th   of 25 Floors           3
8th   of 26 Floors           8
8th   of 27 Floors           1
8th   of 28 Floors           2
8th   of 29 Floors           2
8th   of 30 Floors           5
8th   of 31 Floors           1
8th   of 32 Floors           2
8th   of 34 Floors           2
8th   of 35 Floors           1
8th   of 40 Floors           3
8th   of 42 Floors           1
8th   of 8 Floors           11
8th   of 9 Floors            5
9th   of 10 Floors           4
9th   of 11 Floors           5
9th   of 12 Floors           8
9th   of 13 Floors          17
9th   of 14 Floors          23
9th   of 15 Floors          15
9th   of 16 Floors           3
9th   of 17 Floors           2
9th   of 18 Floors           8
9th   of 19 Floors           7
9th   of 20 Floors           9
9th   of 21 Floors           3
9th   of 22 Floors           5
9th   of 23 Floors           1
9th   of 24 Floors          11
9th   of 25 Floors           1
9th   of 26 Floors          11
9th   of 27 Floors           2
9th   of 28 Floors           2
9th   of 29 Floors           2
9th   of 30 Floors           5
9th   of 40 Floors           3
9th   of 42 Floors           1
9th   of 9 Floors           23
Basement of 13 Floors        1
Basement of 28 Floors        1
Basement of 4 Floors         1
Ground of 1 Floors          17
Ground of 11 Floors          1
Ground of 12 Floors          5
Ground of 13 Floors          4
Ground of 14 Floors         40
Ground of 15 Floors          6
Ground of 16 Floors          6
Ground of 17 Floors          4
Ground of 18 Floors          3
Ground of 19 Floors          5
Ground of 2 Floors           1
Ground of 21 Floors          5
Ground of 22 Floors          1
Ground of 23 Floors          2
Ground of 24 Floors          1
Ground of 25 Floors          1
Ground of 26 Floors          3
Ground of 29 Floors          1
Ground of 3 Floors           6
Ground of 4 Floors          13
Ground of 40 Floors          1
Ground of 5 Floors           1
Ground of 51 Floors          2
Ground of 6 Floors           1
Lower Ground of 1 Floors     1
Lower Ground of 4 Floors     2
Name: count, dtype: int64

In [42]:
df[df['floorNum'].isna()]

,property_name,society,price_in_cr,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [47]:
# independent_houses.csv only contains the floor number on which the flat is located in noOfFloor column. Therefor, only extracting the floor number on which the flat is located

df['floorNum'] = df['floorNum'].str.strip().str.split('of').str.get(0).str.strip().str.lower().replace('ground', '0').replace('basement', '-1').replace('lower', '0').replace('lower ground', '0').str.extract(r'(\d+)').astype('Int64')

In [49]:
df['floorNum'].isna().sum()

np.int64(2)

In [50]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

### Facing column

In [54]:
df['facing'] = df['facing'].str.lower()

In [55]:
df['facing'].isna().sum()

np.int64(874)

In [57]:
df['facing'] = df['facing'].fillna('NA')

### Adding area column from price and sqft

In [ ]:
df.insert(loc=4, column='area', value= ((df['price_in_cr']*10000000) / df['price_per_sqft']).round(2))

In [62]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,west,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,650.03,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,west,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,595.06,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,1345.12,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [67]:
df.shape

(2997, 19)

In [66]:
df[df['property_name'].str.contains('Flat')].shape

(2997, 19)

In [68]:
# all the names of the property contain 'flat'. Adding a column property type to differenciate from independent homes

df.insert(loc= 1, column = 'property_type', value='flat')

In [69]:
df.head()

,property_name,property_type,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,west,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692,650.03,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,west,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722,595.06,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204,1345.12,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [71]:
df.to_csv(r'artifacts\Data\flats_cleaned_1.csv')