In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import os
os.chdir(r'C:\Users\apaks\Desktop\Real Estate Project')

In [ ]:
df = pd.read_csv(r'artifacts\Data\independent-house.csv')

In [ ]:
df.head()

In [ ]:
df.isna().sum()

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
# rows with missing property_id, most of the data is missing. Therefore drop them

df= df[~df['property_id'].isna()]

In [ ]:
df.shape

In [ ]:
# rename rate to price_per_sqft to match the floor file
df.rename(columns= {'rate': 'price_per_sqft'}, inplace = True)

In [ ]:
# drop link and property_id column
df.drop(columns = ['link', 'property_id'], inplace = True)

In [ ]:
# drop duplicates
df.duplicated().sum()
df = df.drop_duplicates()

In [ ]:
df.isnull().sum()

### Society Column

In [ ]:
df['society'].isna().sum()

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
df['society'].value_counts().sort_index()

In [ ]:
df['society']=df['society'].replace('nul', 'independent')

In [ ]:
import re

# remove rating from the name
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [ ]:
df['society'].value_counts().sort_index()

In [ ]:
df['society'].isnull().sum()

In [ ]:
df['society'] = df['society'].replace('nan', 'independent')

In [ ]:
df.head()

### Price column

In [ ]:
df['price'].value_counts().sort_index()

In [ ]:
# drop price on request
df = df[df['price'] != 'Price on Request']

In [ ]:
df['price'] = df['price'].str.strip().str.lower()

In [ ]:
# convert prices to crores and remove 'crore' and 'lac'

def treat_price(price):
    if type(price) == float:
        return price
    else:
        if price[1] == 'lac':
            return float(price[0]) * 0.01
        else:
            return float(price[0])

In [ ]:
df['price'] = df['price'].str.strip().str.split(' ').apply(treat_price).round(2)

In [ ]:
df['price'].isna().sum()

In [ ]:
df.rename(columns = {'price': 'price_in_cr'}, inplace=True)

In [ ]:
df.head()

### price_per_sqft column

In [94]:
df['price_per_sqft'] = df['price_per_sqft'].str.strip().str.extract(r'([\d,]+)')

In [97]:
df['price_per_sqft'] = df['price_per_sqft'].str.replace(',', '')

In [100]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### bedroom, bathroom, balcony column

In [ ]:
# bedroom
df['bedRoom'] = df['bedRoom'].str.strip().str.replace('Bedrooms', '').str.replace('Bedroom', '').str.strip().astype('Int64')
df = df[~df['bedRoom'].isnull()]

In [117]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
#bathroom

df['bathroom'] = df['bathroom'].str.strip().str.split(' ').str.get(0).astype('Int64')
df['bathroom'].isnull().sum()

In [132]:
# balcony
df['balcony'] = df['balcony'].str.replace('No', '0').str.strip().str.split(' ').str.get(0)

In [133]:
df['balcony'].isnull().sum()

np.int64(0)

In [134]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### additional room

In [136]:
df['additionalRoom'].value_counts().sort_index()

additionalRoom
Others                                           58
Pooja Room                                       38
Pooja Room,Others                                11
Pooja Room,Servant Room                          24
Pooja Room,Servant Room,Others                    5
Pooja Room,Servant Room,Store Room                7
Pooja Room,Servant Room,Study Room,Store Room     4
Pooja Room,Store Room                            11
Pooja Room,Store Room,Servant Room                1
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Study Room                            11
Pooja Room,Study Room,Others                      4
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Pooja Room,Study Room,Servant Room,Store Room    60
Pooja Room,Study Room,Store Room                  3
Pooja Room,Study Room,Store Room,Servant Room     2
Servant Room                                     81
Servant Room,Others                               8
Servant Room,Others,Pooja Room                    1
Servant Room,Pooja Room                           8
Servant Room,Pooja Room,Store Room                6
Servant Room,Store Room                          15
Servant Room,Store Room,Pooja Room                4
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room                2
Servant Room,Study Room,Pooja Room,Store Room     5
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room                                       31
Store Room,Pooja Room                             4
Store Room,Pooja Room,Servant Room                2
Store Room,Pooja Room,Servant Room,Study Room     1
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Study Room,Servant Room     2
Store Room,Servant Room                           6
Store Room,Servant Room,Pooja Room                1
Store Room,Servant Room,Study Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Study Room                                       19
Study Room,Others                                 3
Study Room,Others,Servant Room                    1
Study Room,Pooja Room                             2
Study Room,Pooja Room,Servant Room                5
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room                  2
Study Room,Pooja Room,Store Room,Servant Room     2
Study Room,Servant Room                          19
Study Room,Servant Room,Others                    2
Study Room,Servant Room,Pooja Room                3
Study Room,Servant Room,Pooja Room,Store Room     6
Study Room,Servant Room,Store Room                4
Study Room,Servant Room,Store Room,Pooja Room     4
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Study Room,Store Room,Servant Room,Pooja Room     1
Name: count, dtype: int64

In [139]:
df['additionalRoom'] = df['additionalRoom'].fillna('not available').str.lower()

### noOfFloor column

In [143]:
df['noOfFloor'].value_counts().sort_index()

noOfFloor
0 Floors       6
02 Floors      1
1 Floors     181
10 Floors      2
11 Floors      2
12 Floors      2
13 Floors      1
14 Floors      3
16 Floors      1
2 Floors     288
20 Floors      1
21 Floors      1
27 Floors      1
3 Floors     304
33 Floors      1
4 Floors     136
41 Floors      1
5 Floors       9
51 Floors      1
6 Floors       3
Name: count, dtype: int64

In [147]:
df['noOfFloor'] = df['noOfFloor'].str.strip().str.split(' ').str.get(0).astype('Int64')

In [144]:
df['noOfFloor'].isnull().sum()

np.int64(19)

In [149]:
df[df['noOfFloor'].isnull()]

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
23,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,2,"pooja room,servant room,store room","Sector 48 Gurgaon, Gurgaon, Haryana",<NA>,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
51,8 Bedroom House for sale in Palam Vihar,independent,5.60,17284,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8,6,3+,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",<NA>,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
203,3 Bedroom House for sale in DLF Phase 3,independent,1.45,26852,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),3,3,1,not available,"DLF Phase 3, Gurgaon, Haryana",<NA>,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.Pla...,NaN,['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
252,3 Bedroom House for sale in Ashok Vihar,independent,1.50,10288,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,0,not available,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",<NA>,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
270,2 Bedroom House for sale in Laxman Vihar Phase 2,independent,4.12,8889,(431 sq.m.) Plot Area,Plot area 515(430.61 sq.m.),2,1,3+,not available,"Laxman Vihar Phase 2, Gurgaon, Haryana",<NA>,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...","Property next to dhanwapur underpass, which is...",[],NaN,NaN
281,3 Bedroom House for sale in New Palam Vihar Ph...,independent,2.50,5472,(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),3,2,1,not available,"B-245, New Palam Vihar Phase 2, Gurgaon, Haryana",<NA>,NaN,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",100 mtr from dwarka express way. On 40ft road,NaN,['Park'],NaN
374,4 Bedroom House for sale in Laxman Vihar,independent,0.65,11111,(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.),4,2,2,not available,"Laxman Vihar, Gurgaon, Haryana",<NA>,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Well maintained two storeyed independent house...,"['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
397,1 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,3.30,26570,(115 sq.m.) Plot Area,Plot area 138(115.39 sq.m.),1,1,0,not available,"Sushant Lok Phase 1, Gurgaon, Haryana",<NA>,NaN,By 2027,"['Iffco chowk metro station', 'Huda city centr...","Close proximity to gold souk , huda city centr...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
417,2 Bedroom House for sale in Bhawani Enclave,independent,1.10,73333,(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1,others,"Bhawani Enclave, Gurgaon, Haryana",<NA>,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
560,2 Bedroom House for sale in Jacobpura,jacob pura,0.35,9722,(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),2,1,0,not available,"15/3, Jacobpura, Jacobpura, Gurgaon, Haryana",<NA>,NaN,10+ Year Old,NaN,Independece house for sale in jacobpura near k...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
594,6 Bedroom House for sale in DLF Phase 2,independent,13.00,45710,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,8,3+,"pooja room,servant room,study room,store room","DLF Phase 2, Gurgaon, Haryana",<NA>,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
666,3 Bedroom House for sale in New Colony,independent,6.50,15046,(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3,2,3+,not available,"New Colony, Gurgaon, Haryana",<NA>,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
709,12 Bedroom House for sale in Sector 46 Gurgaon,independent,6.81,36911,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),12,14,3+,"servant room,others","Sector 46 Gurgaon, Gurgaon, Haryana",<NA>,East,0 to 1 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 sqyds newly floor wise building with basem...,"['14 Wardrobe', '15 Fan', '1 Exhaust Fan', '13...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
832,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,2.47,7718,(297 sq.m.) Plot Area,Plot area 3200(297.29 sq.m.)Built Up area: 280...,4,4,3+,"pooja room,servant room","Sector 86 Gurgaon, Gurgaon, Haryana",<NA>,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",This is beautiful 4 bhk villa in dlf new town ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
855,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,1,not available,"4 Bed And 4 Bathroom, Sector 48 Gurgaon, Gurga...",<NA>,NaN,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",360 sq yard 4 bhk residential villa for sale i...,"['4 Bed', '4 Fan', '1 Exhaust Fan', '4 Light',...","['Maintenance Staff', 'Water Storage', 'Separa...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
862,4 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok,10.50,27911,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),4,4,2,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",<NA>,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...",Ansal villa for sale 418 sqyd in d block gated...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
865,4 Bedroom House for sale in Sector 26 Gurgaon,independent,4.60,12198,(350 sq.m.) Plot Area,Plot area 419(350.34 sq.m.),4,4,3+,not available,"F-5/10, Sector 26 Gurgaon, Gurgaon, Haryana",<NA>,NaN,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",On the lookout for a spacious house in gurgaon...,[],"['Maintenance Staff', 'Park', 'Visitor Parking...",NaN
1003,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,9.00,21251,(521 sq.m.) Plot Area,Plot area 5605(520.72 sq.m.)Built Up area: 520...,4,4,3+,"pooja room,servant room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",<NA>,South-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",A lifestyle designed to satiate all your sense...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1016,12 Bedroom House for sale in Uppals Southend,uppal southend,6.75,290948,(22 sq.m.) Plot Area,Plot area 232(21.55 sq.m.),12,12,3+,"pooja room,study room,servant room,others","Uppals Southend, Gurgaon, Haryana",<NA>,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [150]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [154]:
df.rename(columns = {'noOfFloor': 'floorNum'}, inplace = True)

### facing column

In [155]:
df['facing'].value_counts().sort_index()

facing
East          178
North         109
North-East    158
North-West     44
South          34
South-East     39
South-West     24
West           75
Name: count, dtype: int64

In [159]:
df['facing']= df['facing'].fillna('NA')

In [160]:
df.head()

,property_name,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [163]:
df.shape

(964, 19)

In [161]:
df.info()

<class 'pandas.DataFrame'>
Index: 964 entries, 0 to 1090
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    str
 1   society          964 non-null    str
 2   price_in_cr      945 non-null    float64
 3   price_per_sqft   945 non-null    str
 4   area             964 non-null    str
 5   areaWithType     964 non-null    str
 6   bedRoom          964 non-null    Int64
 7   bathroom         964 non-null    Int64
 8   balcony          964 non-null    object
 9   additionalRoom   964 non-null    str
 10  address          959 non-null    str
 11  floorNum         945 non-null    Int64
 12  facing           964 non-null    str
 13  agePossession    964 non-null    str
 14  nearbyLocations  848 non-null    str
 15  description      964 non-null    str
 16  furnishDetails   729 non-null    str
 17  features         662 non-null    str
 18  rating           843 non-null    str
dtypes: Int64(3), float64(1), object(1), str(14)
memory usage: 153.4+ KB

In [164]:
df.insert(loc = 1, column = 'propert_type', value='house')

In [165]:
df.head()

,property_name,propert_type,society,price_in_cr,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [166]:
df.to_csv(r'artifacts\Data\independent_house_cleaned_1.csv')