In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\data\preprocessed-data\gurgaon_properties_post_feature_selection.csv')

In [3]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 83,1.18,3,3,2,relatively new,1612.0,0,0,unfurnished,budget,high-rise
1,flat,sector 62,4.00,3,3,3,new,2353.0,1,0,semifurnished,budget,high-rise
2,flat,sector 85,1.10,2,2,3+,relatively new,1459.0,0,1,unfurnished,luxury,low-rise
3,flat,sector 91,0.89,2,2,3+,relatively new,1297.0,0,0,semifurnished,budget,medium-rise
4,flat,sector 7,0.48,3,2,1,new,889.0,0,0,unfurnished,budget,low-rise

In [4]:
df.drop(columns = ['store room', 'floor_category', 'balcony'], inplace = True)

In [5]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 83,1.18,3,3,relatively new,1612.0,0,unfurnished,budget
1,flat,sector 62,4.00,3,3,new,2353.0,1,semifurnished,budget
2,flat,sector 85,1.10,2,2,relatively new,1459.0,0,unfurnished,luxury
3,flat,sector 91,0.89,2,2,relatively new,1297.0,0,semifurnished,budget
4,flat,sector 7,0.48,3,2,new,889.0,0,unfurnished,budget

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3499 entries, 0 to 3498
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3499 non-null   object
 1   sector           3499 non-null   object
 2   price            3499 non-null   float64
 3   bedRoom          3499 non-null   int64
 4   bathroom         3499 non-null   int64
 5   agePossession    3499 non-null   object
 6   built_up_area    3499 non-null   float64
 7   servant room     3499 non-null   int64
 8   furnishing_type  3499 non-null   object
 9   luxury_category  3499 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 273.5+ KB

In [7]:
df['agePossession'].value_counts()

agePossession
relatively new        1689
new                    632
relatively old         569
old                    328
under construction     281
Name: count, dtype: int64

In [8]:
df['agePossession'].replace({
    'relatively new': 'new',
    'relatively old': 'old'
}, inplace = True)

C:\Users\apaks\AppData\Local\Temp\ipykernel_15924\3576781748.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['agePossession'].replace({

In [9]:
df['agePossession'].value_counts()

agePossession
new                   2321
old                    897
under construction     281
Name: count, dtype: int64

In [10]:
df['furnishing_type'].value_counts()

furnishing_type
unfurnished      2296
semifurnished    1009
furnished         194
Name: count, dtype: int64

In [11]:
df['furnishing_type'].replace({
    'unfurnished': 0,
    'semifurnished': 1,
    'furnished': 2
}, inplace = True)

C:\Users\apaks\AppData\Local\Temp\ipykernel_15924\1974551245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['furnishing_type'].replace({
C:\Users\apaks\AppData\Local\Temp\ipykernel_15924\1974551245.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['furnishing_type'].replace({

In [12]:
df['furnishing_type'].value_counts()

furnishing_type
0    2296
1    1009
2     194
Name: count, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3499 entries, 0 to 3498
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3499 non-null   object
 1   sector           3499 non-null   object
 2   price            3499 non-null   float64
 3   bedRoom          3499 non-null   int64
 4   bathroom         3499 non-null   int64
 5   agePossession    3499 non-null   object
 6   built_up_area    3499 non-null   float64
 7   servant room     3499 non-null   int64
 8   furnishing_type  3499 non-null   int64
 9   luxury_category  3499 non-null   object
dtypes: float64(2), int64(4), object(4)
memory usage: 273.5+ KB

In [14]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 83,1.18,3,3,new,1612.0,0,0,budget
1,flat,sector 62,4.00,3,3,new,2353.0,1,1,budget
2,flat,sector 85,1.10,2,2,new,1459.0,0,0,luxury
3,flat,sector 91,0.89,2,2,new,1297.0,0,1,budget
4,flat,sector 7,0.48,3,2,new,889.0,0,0,budget

In [16]:
df['property_type'] = df['property_type'].replace({
    'flat': 0,
    'house': 1
})

C:\Users\apaks\AppData\Local\Temp\ipykernel_15924\3923419486.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({

In [17]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 83,1.18,3,3,new,1612.0,0,0,budget
1,0,sector 62,4.00,3,3,new,2353.0,1,1,budget
2,0,sector 85,1.10,2,2,new,1459.0,0,0,luxury
3,0,sector 91,0.89,2,2,new,1297.0,0,1,budget
4,0,sector 7,0.48,3,2,new,889.0,0,0,budget

In [18]:
df['luxury_category'].value_counts()

luxury_category
semi-luxury    1466
budget         1298
luxury          735
Name: count, dtype: int64

In [19]:
df['luxury_category'] = df['luxury_category'].replace({
    'budget': 0,
    'semi-luxury': 1, 
    'luxury': 2
})

C:\Users\apaks\AppData\Local\Temp\ipykernel_15924\2374599039.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({

In [20]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 83,1.18,3,3,new,1612.0,0,0,0
1,0,sector 62,4.00,3,3,new,2353.0,1,1,0
2,0,sector 85,1.10,2,2,new,1459.0,0,0,2
3,0,sector 91,0.89,2,2,new,1297.0,0,1,0
4,0,sector 7,0.48,3,2,new,889.0,0,0,0

In [23]:
# ohe on sector and agePossesion

df_transformed = pd.get_dummies(df, columns = ['sector', 'agePossession'], drop_first=True, dtype=int)

In [24]:
# split X and y

X = df_transformed.drop(columns = 'price')
y = df_transformed['price']

In [27]:
y_log = np.log1p(y)

In [28]:
y_log

0       0.779325
1       1.609438
2       0.741937
3       0.636577
4       0.392042
          ...
3494    0.854415
3495    2.803360
3496    1.131402
3497    1.011601
3498    0.542324
Name: price, Length: 3499, dtype: float64

In [30]:
# scaling the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [32]:
X_scaled = pd.DataFrame(X_scaled, columns = X.columns)

In [33]:
# train Linear Regression model

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score

kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv = kfold, scoring='r2')

In [34]:
scores.mean()

np.float64(0.8476767700844346)

In [35]:
scores.std()

np.float64(0.01845941178569959)

In [36]:
lr = LinearRegression()
lr.fit(X_scaled, y_log)

LinearRegression()

In [45]:
coef_df = pd.DataFrame(lr.coef_.reshape(1, 103), columns = X.columns).stack().reset_index().drop(columns = 'level_0').rename(columns = {'level_1': 'feature_name', 0:'coef'})

In [73]:
coef_df.iloc[:10]

        feature_name      coef
0      property_type  0.120067
1            bedRoom  0.048897
2           bathroom  0.063360
3      built_up_area  0.212184
4       servant room  0.053837
5    furnishing_type  0.011268
6    luxury_category  0.006736
7   sector_sector 10  0.011387
8  sector_sector 102  0.068555
9  sector_sector 103  0.022741

In [49]:
X['bedRoom'].std()

np.float64(1.2725994483161271)

In [53]:
y_log.std()

np.float64(0.5526176961964918)

In [56]:
np.expm1(0.048897 * (y.std()/ X['bedRoom'].std()))

np.float64(0.11398589294960498)

In [74]:
coef = 0.011268
sigma_x = X['furnishing_type'].std()

delta_log_y = coef / sigma_x
pct_change = (np.exp(delta_log_y) - 1) * 100
pct_change
np.exp(delta_log_y)

np.float64(1.0192056848936728)

In [75]:
import pickle

In [76]:
model = pickle.load(open(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\model.pkl', 'rb'))

In [77]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(model, X_scaled, y_log, cv = kfold, scoring='r2')

In [78]:
print(scores.mean())
print(scores.std())

0.8795029051907018
0.008825430914641465

In [ ]:
# shap explainer for the model
import shap

explainer = shap.TreeExplainer(model)